# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.condition_schema import ConditionSchema
from artifactsmmo.models.map_access_type import MapAccessType
from artifactsmmo import util


class AccessSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type: MapAccessType=None, conditions: List[ConditionSchema]=None):
        """AccessSchema - a model defined in OpenAPI

        :param type: The type of this AccessSchema.
        :param conditions: The conditions of this AccessSchema.
        """
        self.openapi_types = {
            'type': MapAccessType,
            'conditions': List[ConditionSchema]
        }

        self.attribute_map = {
            'type': 'type',
            'conditions': 'conditions'
        }

        self._type = type
        self._conditions = conditions

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AccessSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AccessSchema of this AccessSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this AccessSchema.

        Map access type determining movement and accessibility

        :return: The type of this AccessSchema.
        :rtype: MapAccessType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AccessSchema.

        Map access type determining movement and accessibility

        :param type: The type of this AccessSchema.
        :type type: MapAccessType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def conditions(self):
        """Gets the conditions of this AccessSchema.

        Access conditions for the map

        :return: The conditions of this AccessSchema.
        :rtype: List[ConditionSchema]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this AccessSchema.

        Access conditions for the map

        :param conditions: The conditions of this AccessSchema.
        :type conditions: List[ConditionSchema]
        """

        self._conditions = conditions
