# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.account_status import AccountStatus
from artifactsmmo import util


class AccountLeaderboardSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, position: int=None, account: str=None, status: AccountStatus=None, achievements_points: int=None, gold: int=None):
        """AccountLeaderboardSchema - a model defined in OpenAPI

        :param position: The position of this AccountLeaderboardSchema.
        :param account: The account of this AccountLeaderboardSchema.
        :param status: The status of this AccountLeaderboardSchema.
        :param achievements_points: The achievements_points of this AccountLeaderboardSchema.
        :param gold: The gold of this AccountLeaderboardSchema.
        """
        self.openapi_types = {
            'position': int,
            'account': str,
            'status': AccountStatus,
            'achievements_points': int,
            'gold': int
        }

        self.attribute_map = {
            'position': 'position',
            'account': 'account',
            'status': 'status',
            'achievements_points': 'achievements_points',
            'gold': 'gold'
        }

        self._position = position
        self._account = account
        self._status = status
        self._achievements_points = achievements_points
        self._gold = gold

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AccountLeaderboardSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AccountLeaderboardSchema of this AccountLeaderboardSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def position(self):
        """Gets the position of this AccountLeaderboardSchema.

        Position in the leaderboard.

        :return: The position of this AccountLeaderboardSchema.
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this AccountLeaderboardSchema.

        Position in the leaderboard.

        :param position: The position of this AccountLeaderboardSchema.
        :type position: int
        """
        if position is None:
            raise ValueError("Invalid value for `position`, must not be `None`")

        self._position = position

    @property
    def account(self):
        """Gets the account of this AccountLeaderboardSchema.

        Account name.

        :return: The account of this AccountLeaderboardSchema.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this AccountLeaderboardSchema.

        Account name.

        :param account: The account of this AccountLeaderboardSchema.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")

        self._account = account

    @property
    def status(self):
        """Gets the status of this AccountLeaderboardSchema.

        Member status.

        :return: The status of this AccountLeaderboardSchema.
        :rtype: AccountStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AccountLeaderboardSchema.

        Member status.

        :param status: The status of this AccountLeaderboardSchema.
        :type status: AccountStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")

        self._status = status

    @property
    def achievements_points(self):
        """Gets the achievements_points of this AccountLeaderboardSchema.

        Achievements points.

        :return: The achievements_points of this AccountLeaderboardSchema.
        :rtype: int
        """
        return self._achievements_points

    @achievements_points.setter
    def achievements_points(self, achievements_points):
        """Sets the achievements_points of this AccountLeaderboardSchema.

        Achievements points.

        :param achievements_points: The achievements_points of this AccountLeaderboardSchema.
        :type achievements_points: int
        """
        if achievements_points is None:
            raise ValueError("Invalid value for `achievements_points`, must not be `None`")

        self._achievements_points = achievements_points

    @property
    def gold(self):
        """Gets the gold of this AccountLeaderboardSchema.

        Gold in the account.

        :return: The gold of this AccountLeaderboardSchema.
        :rtype: int
        """
        return self._gold

    @gold.setter
    def gold(self, gold):
        """Sets the gold of this AccountLeaderboardSchema.

        Gold in the account.

        :param gold: The gold of this AccountLeaderboardSchema.
        :type gold: int
        """
        if gold is None:
            raise ValueError("Invalid value for `gold`, must not be `None`")

        self._gold = gold
