# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.achievement_type import AchievementType
from artifactsmmo import util


class AccountAchievementObjectiveSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type: AchievementType=None, target: str=None, progress: int=0, total: int=None):
        """AccountAchievementObjectiveSchema - a model defined in OpenAPI

        :param type: The type of this AccountAchievementObjectiveSchema.
        :param target: The target of this AccountAchievementObjectiveSchema.
        :param progress: The progress of this AccountAchievementObjectiveSchema.
        :param total: The total of this AccountAchievementObjectiveSchema.
        """
        self.openapi_types = {
            'type': AchievementType,
            'target': str,
            'progress': int,
            'total': int
        }

        self.attribute_map = {
            'type': 'type',
            'target': 'target',
            'progress': 'progress',
            'total': 'total'
        }

        self._type = type
        self._target = target
        self._progress = progress
        self._total = total

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AccountAchievementObjectiveSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AccountAchievementObjectiveSchema of this AccountAchievementObjectiveSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self):
        """Gets the type of this AccountAchievementObjectiveSchema.

        Type of objective.

        :return: The type of this AccountAchievementObjectiveSchema.
        :rtype: AchievementType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AccountAchievementObjectiveSchema.

        Type of objective.

        :param type: The type of this AccountAchievementObjectiveSchema.
        :type type: AchievementType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def target(self):
        """Gets the target of this AccountAchievementObjectiveSchema.

        Target of the objective (e.g., item code, monster code).

        :return: The target of this AccountAchievementObjectiveSchema.
        :rtype: str
        """
        return self._target

    @target.setter
    def target(self, target):
        """Sets the target of this AccountAchievementObjectiveSchema.

        Target of the objective (e.g., item code, monster code).

        :param target: The target of this AccountAchievementObjectiveSchema.
        :type target: str
        """

        self._target = target

    @property
    def progress(self):
        """Gets the progress of this AccountAchievementObjectiveSchema.

        Current progress for this objective.

        :return: The progress of this AccountAchievementObjectiveSchema.
        :rtype: int
        """
        return self._progress

    @progress.setter
    def progress(self, progress):
        """Sets the progress of this AccountAchievementObjectiveSchema.

        Current progress for this objective.

        :param progress: The progress of this AccountAchievementObjectiveSchema.
        :type progress: int
        """

        self._progress = progress

    @property
    def total(self):
        """Gets the total of this AccountAchievementObjectiveSchema.

        Total required for this objective.

        :return: The total of this AccountAchievementObjectiveSchema.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this AccountAchievementObjectiveSchema.

        Total required for this objective.

        :param total: The total of this AccountAchievementObjectiveSchema.
        :type total: int
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")

        self._total = total
