# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.achievement_schema import AchievementSchema
from artifactsmmo import util


class AchievementResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: AchievementSchema=None):
        """AchievementResponseSchema - a model defined in OpenAPI

        :param data: The data of this AchievementResponseSchema.
        """
        self.openapi_types = {
            'data': AchievementSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AchievementResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AchievementResponseSchema of this AchievementResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this AchievementResponseSchema.


        :return: The data of this AchievementResponseSchema.
        :rtype: AchievementSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this AchievementResponseSchema.


        :param data: The data of this AchievementResponseSchema.
        :type data: AchievementSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
