# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.achievement_objective_schema import AchievementObjectiveSchema
from artifactsmmo.models.achievement_rewards_schema import AchievementRewardsSchema
from artifactsmmo import util


class AchievementSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, code: str=None, description: str=None, points: int=None, objectives: List[AchievementObjectiveSchema]=None, rewards: AchievementRewardsSchema=None):
        """AchievementSchema - a model defined in OpenAPI

        :param name: The name of this AchievementSchema.
        :param code: The code of this AchievementSchema.
        :param description: The description of this AchievementSchema.
        :param points: The points of this AchievementSchema.
        :param objectives: The objectives of this AchievementSchema.
        :param rewards: The rewards of this AchievementSchema.
        """
        self.openapi_types = {
            'name': str,
            'code': str,
            'description': str,
            'points': int,
            'objectives': List[AchievementObjectiveSchema],
            'rewards': AchievementRewardsSchema
        }

        self.attribute_map = {
            'name': 'name',
            'code': 'code',
            'description': 'description',
            'points': 'points',
            'objectives': 'objectives',
            'rewards': 'rewards'
        }

        self._name = name
        self._code = code
        self._description = description
        self._points = points
        self._objectives = objectives
        self._rewards = rewards

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AchievementSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AchievementSchema of this AchievementSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this AchievementSchema.

        Name of the achievement.

        :return: The name of this AchievementSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AchievementSchema.

        Name of the achievement.

        :param name: The name of this AchievementSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def code(self):
        """Gets the code of this AchievementSchema.

        Code of the achievement.

        :return: The code of this AchievementSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this AchievementSchema.

        Code of the achievement.

        :param code: The code of this AchievementSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def description(self):
        """Gets the description of this AchievementSchema.

        Description of the achievement.

        :return: The description of this AchievementSchema.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AchievementSchema.

        Description of the achievement.

        :param description: The description of this AchievementSchema.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")

        self._description = description

    @property
    def points(self):
        """Gets the points of this AchievementSchema.

        Points of the achievement. Used for the leaderboard.

        :return: The points of this AchievementSchema.
        :rtype: int
        """
        return self._points

    @points.setter
    def points(self, points):
        """Sets the points of this AchievementSchema.

        Points of the achievement. Used for the leaderboard.

        :param points: The points of this AchievementSchema.
        :type points: int
        """
        if points is None:
            raise ValueError("Invalid value for `points`, must not be `None`")

        self._points = points

    @property
    def objectives(self):
        """Gets the objectives of this AchievementSchema.

        List of objectives that must be completed.

        :return: The objectives of this AchievementSchema.
        :rtype: List[AchievementObjectiveSchema]
        """
        return self._objectives

    @objectives.setter
    def objectives(self, objectives):
        """Sets the objectives of this AchievementSchema.

        List of objectives that must be completed.

        :param objectives: The objectives of this AchievementSchema.
        :type objectives: List[AchievementObjectiveSchema]
        """
        if objectives is None:
            raise ValueError("Invalid value for `objectives`, must not be `None`")

        self._objectives = objectives

    @property
    def rewards(self):
        """Gets the rewards of this AchievementSchema.

        Rewards.

        :return: The rewards of this AchievementSchema.
        :rtype: AchievementRewardsSchema
        """
        return self._rewards

    @rewards.setter
    def rewards(self, rewards):
        """Sets the rewards of this AchievementSchema.

        Rewards.

        :param rewards: The rewards of this AchievementSchema.
        :type rewards: AchievementRewardsSchema
        """
        if rewards is None:
            raise ValueError("Invalid value for `rewards`, must not be `None`")

        self._rewards = rewards
