# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class AchievementType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    COMBAT_KILL = 'combat_kill'
    COMBAT_DROP = 'combat_drop'
    COMBAT_LEVEL = 'combat_level'
    GATHERING = 'gathering'
    CRAFTING = 'crafting'
    RECYCLING = 'recycling'
    TASK = 'task'
    OTHER = 'other'
    USE = 'use'
    NPC_BUY = 'npc_buy'
    NPC_SELL = 'npc_sell'

    def __init__(self):
        """AchievementType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AchievementType':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AchievementType of this AchievementType.
        """
        return util.deserialize_model(dikt, cls)
