# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class ActionType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    MOVEMENT = 'movement'
    FIGHT = 'fight'
    MULTI_FIGHT = 'multi_fight'
    CRAFTING = 'crafting'
    GATHERING = 'gathering'
    BUY_GE = 'buy_ge'
    SELL_GE = 'sell_ge'
    CREATE_BUY_ORDER_GE = 'create_buy_order_ge'
    FILL_BUY_ORDER_GE = 'fill_buy_order_ge'
    BUY_NPC = 'buy_npc'
    SELL_NPC = 'sell_npc'
    CANCEL_GE = 'cancel_ge'
    DELETE_ITEM = 'delete_item'
    DEPOSIT_ITEM = 'deposit_item'
    WITHDRAW_ITEM = 'withdraw_item'
    DEPOSIT_GOLD = 'deposit_gold'
    WITHDRAW_GOLD = 'withdraw_gold'
    EQUIP = 'equip'
    UNEQUIP = 'unequip'
    TASK = 'task'
    RECYCLING = 'recycling'
    REST = 'rest'
    USE = 'use'
    BUY_BANK_EXPANSION = 'buy_bank_expansion'
    GIVE_ITEM = 'give_item'
    GIVE_GOLD = 'give_gold'
    CHANGE_SKIN = 'change_skin'
    RENAME = 'rename'
    TRANSITION = 'transition'
    CLAIM_ITEM = 'claim_item'

    def __init__(self):
        """ActionType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ActionType':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ActionType of this ActionType.
        """
        return util.deserialize_model(dikt, cls)
