# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.map_schema import MapSchema
from artifactsmmo import util


class ActiveEventSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, code: str=None, map: MapSchema=None, previous_map: MapSchema=None, duration: int=None, expiration: datetime=None, created_at: datetime=None):
        """ActiveEventSchema - a model defined in OpenAPI

        :param name: The name of this ActiveEventSchema.
        :param code: The code of this ActiveEventSchema.
        :param map: The map of this ActiveEventSchema.
        :param previous_map: The previous_map of this ActiveEventSchema.
        :param duration: The duration of this ActiveEventSchema.
        :param expiration: The expiration of this ActiveEventSchema.
        :param created_at: The created_at of this ActiveEventSchema.
        """
        self.openapi_types = {
            'name': str,
            'code': str,
            'map': MapSchema,
            'previous_map': MapSchema,
            'duration': int,
            'expiration': datetime,
            'created_at': datetime
        }

        self.attribute_map = {
            'name': 'name',
            'code': 'code',
            'map': 'map',
            'previous_map': 'previous_map',
            'duration': 'duration',
            'expiration': 'expiration',
            'created_at': 'created_at'
        }

        self._name = name
        self._code = code
        self._map = map
        self._previous_map = previous_map
        self._duration = duration
        self._expiration = expiration
        self._created_at = created_at

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ActiveEventSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ActiveEventSchema of this ActiveEventSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ActiveEventSchema.

        Name of the event.

        :return: The name of this ActiveEventSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ActiveEventSchema.

        Name of the event.

        :param name: The name of this ActiveEventSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def code(self):
        """Gets the code of this ActiveEventSchema.

        Code of the event.

        :return: The code of this ActiveEventSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ActiveEventSchema.

        Code of the event.

        :param code: The code of this ActiveEventSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def map(self):
        """Gets the map of this ActiveEventSchema.

        Map of the event.

        :return: The map of this ActiveEventSchema.
        :rtype: MapSchema
        """
        return self._map

    @map.setter
    def map(self, map):
        """Sets the map of this ActiveEventSchema.

        Map of the event.

        :param map: The map of this ActiveEventSchema.
        :type map: MapSchema
        """
        if map is None:
            raise ValueError("Invalid value for `map`, must not be `None`")

        self._map = map

    @property
    def previous_map(self):
        """Gets the previous_map of this ActiveEventSchema.

        Previous map skin.

        :return: The previous_map of this ActiveEventSchema.
        :rtype: MapSchema
        """
        return self._previous_map

    @previous_map.setter
    def previous_map(self, previous_map):
        """Sets the previous_map of this ActiveEventSchema.

        Previous map skin.

        :param previous_map: The previous_map of this ActiveEventSchema.
        :type previous_map: MapSchema
        """
        if previous_map is None:
            raise ValueError("Invalid value for `previous_map`, must not be `None`")

        self._previous_map = previous_map

    @property
    def duration(self):
        """Gets the duration of this ActiveEventSchema.

        Duration in minutes.

        :return: The duration of this ActiveEventSchema.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this ActiveEventSchema.

        Duration in minutes.

        :param duration: The duration of this ActiveEventSchema.
        :type duration: int
        """
        if duration is None:
            raise ValueError("Invalid value for `duration`, must not be `None`")

        self._duration = duration

    @property
    def expiration(self):
        """Gets the expiration of this ActiveEventSchema.

        Expiration datetime.

        :return: The expiration of this ActiveEventSchema.
        :rtype: datetime
        """
        return self._expiration

    @expiration.setter
    def expiration(self, expiration):
        """Sets the expiration of this ActiveEventSchema.

        Expiration datetime.

        :param expiration: The expiration of this ActiveEventSchema.
        :type expiration: datetime
        """
        if expiration is None:
            raise ValueError("Invalid value for `expiration`, must not be `None`")

        self._expiration = expiration

    @property
    def created_at(self):
        """Gets the created_at of this ActiveEventSchema.

        Start datetime.

        :return: The created_at of this ActiveEventSchema.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this ActiveEventSchema.

        Start datetime.

        :param created_at: The created_at of this ActiveEventSchema.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")

        self._created_at = created_at
