# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_skin import CharacterSkin
from artifactsmmo.models.map_layer import MapLayer
from artifactsmmo import util


class ActiveCharacterSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, account: str=None, skin: CharacterSkin=None, x: int=None, y: int=None, layer: MapLayer=None, map_id: int=None):
        """ActiveCharacterSchema - a model defined in OpenAPI

        :param name: The name of this ActiveCharacterSchema.
        :param account: The account of this ActiveCharacterSchema.
        :param skin: The skin of this ActiveCharacterSchema.
        :param x: The x of this ActiveCharacterSchema.
        :param y: The y of this ActiveCharacterSchema.
        :param layer: The layer of this ActiveCharacterSchema.
        :param map_id: The map_id of this ActiveCharacterSchema.
        """
        self.openapi_types = {
            'name': str,
            'account': str,
            'skin': CharacterSkin,
            'x': int,
            'y': int,
            'layer': MapLayer,
            'map_id': int
        }

        self.attribute_map = {
            'name': 'name',
            'account': 'account',
            'skin': 'skin',
            'x': 'x',
            'y': 'y',
            'layer': 'layer',
            'map_id': 'map_id'
        }

        self._name = name
        self._account = account
        self._skin = skin
        self._x = x
        self._y = y
        self._layer = layer
        self._map_id = map_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ActiveCharacterSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ActiveCharacterSchema of this ActiveCharacterSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ActiveCharacterSchema.

        Name of the character.

        :return: The name of this ActiveCharacterSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ActiveCharacterSchema.

        Name of the character.

        :param name: The name of this ActiveCharacterSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def account(self):
        """Gets the account of this ActiveCharacterSchema.

        Account name.

        :return: The account of this ActiveCharacterSchema.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this ActiveCharacterSchema.

        Account name.

        :param account: The account of this ActiveCharacterSchema.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")

        self._account = account

    @property
    def skin(self):
        """Gets the skin of this ActiveCharacterSchema.

        Character skin code.

        :return: The skin of this ActiveCharacterSchema.
        :rtype: CharacterSkin
        """
        return self._skin

    @skin.setter
    def skin(self, skin):
        """Sets the skin of this ActiveCharacterSchema.

        Character skin code.

        :param skin: The skin of this ActiveCharacterSchema.
        :type skin: CharacterSkin
        """
        if skin is None:
            raise ValueError("Invalid value for `skin`, must not be `None`")

        self._skin = skin

    @property
    def x(self):
        """Gets the x of this ActiveCharacterSchema.

        Character x coordinate.

        :return: The x of this ActiveCharacterSchema.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this ActiveCharacterSchema.

        Character x coordinate.

        :param x: The x of this ActiveCharacterSchema.
        :type x: int
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")

        self._x = x

    @property
    def y(self):
        """Gets the y of this ActiveCharacterSchema.

        Character y coordinate.

        :return: The y of this ActiveCharacterSchema.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this ActiveCharacterSchema.

        Character y coordinate.

        :param y: The y of this ActiveCharacterSchema.
        :type y: int
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")

        self._y = y

    @property
    def layer(self):
        """Gets the layer of this ActiveCharacterSchema.

        Character current layer.

        :return: The layer of this ActiveCharacterSchema.
        :rtype: MapLayer
        """
        return self._layer

    @layer.setter
    def layer(self, layer):
        """Sets the layer of this ActiveCharacterSchema.

        Character current layer.

        :param layer: The layer of this ActiveCharacterSchema.
        :type layer: MapLayer
        """
        if layer is None:
            raise ValueError("Invalid value for `layer`, must not be `None`")

        self._layer = layer

    @property
    def map_id(self):
        """Gets the map_id of this ActiveCharacterSchema.

        Character current map ID.

        :return: The map_id of this ActiveCharacterSchema.
        :rtype: int
        """
        return self._map_id

    @map_id.setter
    def map_id(self, map_id):
        """Sets the map_id of this ActiveCharacterSchema.

        Character current map ID.

        :param map_id: The map_id of this ActiveCharacterSchema.
        :type map_id: int
        """
        if map_id is None:
            raise ValueError("Invalid value for `map_id`, must not be `None`")

        self._map_id = map_id
