# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
import re
from artifactsmmo import util


class AddAccountSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, password: str=None, email: str=None):
        """AddAccountSchema - a model defined in OpenAPI

        :param username: The username of this AddAccountSchema.
        :param password: The password of this AddAccountSchema.
        :param email: The email of this AddAccountSchema.
        """
        self.openapi_types = {
            'username': str,
            'password': str,
            'email': str
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password',
            'email': 'email'
        }

        self._username = username
        self._password = password
        self._email = email

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AddAccountSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AddAccountSchema of this AddAccountSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this AddAccountSchema.

        Your desired username.

        :return: The username of this AddAccountSchema.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this AddAccountSchema.

        Your desired username.

        :param username: The username of this AddAccountSchema.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")
        if username is not None and len(username) > 32:
            raise ValueError("Invalid value for `username`, length must be less than or equal to `32`")
        if username is not None and len(username) < 6:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `6`")
        if username is not None and not re.search(r'^[a-zA-Z0-9_-]+$', username):
            raise ValueError("Invalid value for `username`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._username = username

    @property
    def password(self):
        """Gets the password of this AddAccountSchema.

        Your password.

        :return: The password of this AddAccountSchema.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AddAccountSchema.

        Your password.

        :param password: The password of this AddAccountSchema.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")
        if password is not None and len(password) > 50:
            raise ValueError("Invalid value for `password`, length must be less than or equal to `50`")
        if password is not None and len(password) < 5:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `5`")
        # if password is not None and not re.search(r'^[^\s]+$', password):
        #     raise ValueError("Invalid value for `password`, must be a follow pattern or equal to `/^[^\s]+$/`")

        self._password = password

    @property
    def email(self):
        """Gets the email of this AddAccountSchema.

        Your email.

        :return: The email of this AddAccountSchema.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this AddAccountSchema.

        Your email.

        :param email: The email of this AddAccountSchema.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email
