# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_skin import CharacterSkin
import re
from artifactsmmo import util


class AddCharacterSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, skin: CharacterSkin=None):
        """AddCharacterSchema - a model defined in OpenAPI

        :param name: The name of this AddCharacterSchema.
        :param skin: The skin of this AddCharacterSchema.
        """
        self.openapi_types = {
            'name': str,
            'skin': CharacterSkin
        }

        self.attribute_map = {
            'name': 'name',
            'skin': 'skin'
        }

        self._name = name
        self._skin = skin

    @classmethod
    def from_dict(cls, dikt: dict) -> 'AddCharacterSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The AddCharacterSchema of this AddCharacterSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this AddCharacterSchema.

        Your desired character name. It's unique and all players can see it.

        :return: The name of this AddCharacterSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AddCharacterSchema.

        Your desired character name. It's unique and all players can see it.

        :param name: The name of this AddCharacterSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")
        if name is not None and len(name) > 12:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `12`")
        if name is not None and len(name) < 3:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `3`")
        if name is not None and not re.search(r'^[a-zA-Z0-9_-]+$', name):
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._name = name

    @property
    def skin(self):
        """Gets the skin of this AddCharacterSchema.

        Your desired skin. Skins unlocked by default: 'men1', 'men2', 'men3', 'women1', 'women2', 'women3'.

        :return: The skin of this AddCharacterSchema.
        :rtype: CharacterSkin
        """
        return self._skin

    @skin.setter
    def skin(self, skin):
        """Sets the skin of this AddCharacterSchema.

        Your desired skin. Skins unlocked by default: 'men1', 'men2', 'men3', 'women1', 'women2', 'women3'.

        :param skin: The skin of this AddCharacterSchema.
        :type skin: CharacterSkin
        """
        if skin is None:
            raise ValueError("Invalid value for `skin`, must not be `None`")

        self._skin = skin
