# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class BadgeConditionSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, quantity: int=None):
        """BadgeConditionSchema - a model defined in OpenAPI

        :param code: The code of this BadgeConditionSchema.
        :param quantity: The quantity of this BadgeConditionSchema.
        """
        self.openapi_types = {
            'code': str,
            'quantity': int
        }

        self.attribute_map = {
            'code': 'code',
            'quantity': 'quantity'
        }

        self._code = code
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BadgeConditionSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BadgeConditionSchema of this BadgeConditionSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this BadgeConditionSchema.

        Code of the condition.

        :return: The code of this BadgeConditionSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this BadgeConditionSchema.

        Code of the condition.

        :param code: The code of this BadgeConditionSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def quantity(self):
        """Gets the quantity of this BadgeConditionSchema.

        Quantity of the condition (if any).

        :return: The quantity of this BadgeConditionSchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this BadgeConditionSchema.

        Quantity of the condition (if any).

        :param quantity: The quantity of this BadgeConditionSchema.
        :type quantity: int
        """

        self._quantity = quantity
