# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.badge_schema import BadgeSchema
from artifactsmmo import util


class BadgeResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: BadgeSchema=None):
        """BadgeResponseSchema - a model defined in OpenAPI

        :param data: The data of this BadgeResponseSchema.
        """
        self.openapi_types = {
            'data': BadgeSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BadgeResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BadgeResponseSchema of this BadgeResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this BadgeResponseSchema.


        :return: The data of this BadgeResponseSchema.
        :rtype: BadgeSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this BadgeResponseSchema.


        :param data: The data of this BadgeResponseSchema.
        :type data: BadgeSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
