# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.bank_item_transaction_schema import BankItemTransactionSchema
from artifactsmmo import util


class BankItemTransactionResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: BankItemTransactionSchema=None):
        """BankItemTransactionResponseSchema - a model defined in OpenAPI

        :param data: The data of this BankItemTransactionResponseSchema.
        """
        self.openapi_types = {
            'data': BankItemTransactionSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BankItemTransactionResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BankItemTransactionResponseSchema of this BankItemTransactionResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this BankItemTransactionResponseSchema.


        :return: The data of this BankItemTransactionResponseSchema.
        :rtype: BankItemTransactionSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this BankItemTransactionResponseSchema.


        :param data: The data of this BankItemTransactionResponseSchema.
        :type data: BankItemTransactionSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
