# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class BankExtensionSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, price: int=None):
        """BankExtensionSchema - a model defined in OpenAPI

        :param price: The price of this BankExtensionSchema.
        """
        self.openapi_types = {
            'price': int
        }

        self.attribute_map = {
            'price': 'price'
        }

        self._price = price

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BankExtensionSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BankExtensionSchema of this BankExtensionSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def price(self):
        """Gets the price of this BankExtensionSchema.

        Price of the bank extension.

        :return: The price of this BankExtensionSchema.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this BankExtensionSchema.

        Price of the bank extension.

        :param price: The price of this BankExtensionSchema.
        :type price: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")
        if price is not None and price < 0:
            raise ValueError("Invalid value for `price`, must be a value greater than or equal to `0`")

        self._price = price
