# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo.models.simple_item_schema import SimpleItemSchema
from artifactsmmo import util


class BankItemTransactionSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, items: List[SimpleItemSchema]=None, bank: List[SimpleItemSchema]=None, character: CharacterSchema=None):
        """BankItemTransactionSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this BankItemTransactionSchema.
        :param items: The items of this BankItemTransactionSchema.
        :param bank: The bank of this BankItemTransactionSchema.
        :param character: The character of this BankItemTransactionSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'items': List[SimpleItemSchema],
            'bank': List[SimpleItemSchema],
            'character': CharacterSchema
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'items': 'items',
            'bank': 'bank',
            'character': 'character'
        }

        self._cooldown = cooldown
        self._items = items
        self._bank = bank
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BankItemTransactionSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BankItemTransactionSchema of this BankItemTransactionSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this BankItemTransactionSchema.

        Cooldown details.

        :return: The cooldown of this BankItemTransactionSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this BankItemTransactionSchema.

        Cooldown details.

        :param cooldown: The cooldown of this BankItemTransactionSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def items(self):
        """Gets the items of this BankItemTransactionSchema.

        Items details.

        :return: The items of this BankItemTransactionSchema.
        :rtype: List[SimpleItemSchema]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this BankItemTransactionSchema.

        Items details.

        :param items: The items of this BankItemTransactionSchema.
        :type items: List[SimpleItemSchema]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")

        self._items = items

    @property
    def bank(self):
        """Gets the bank of this BankItemTransactionSchema.

        Items in your banks.

        :return: The bank of this BankItemTransactionSchema.
        :rtype: List[SimpleItemSchema]
        """
        return self._bank

    @bank.setter
    def bank(self, bank):
        """Sets the bank of this BankItemTransactionSchema.

        Items in your banks.

        :param bank: The bank of this BankItemTransactionSchema.
        :type bank: List[SimpleItemSchema]
        """
        if bank is None:
            raise ValueError("Invalid value for `bank`, must not be `None`")

        self._bank = bank

    @property
    def character(self):
        """Gets the character of this BankItemTransactionSchema.

        Player details.

        :return: The character of this BankItemTransactionSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this BankItemTransactionSchema.

        Player details.

        :param character: The character of this BankItemTransactionSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
