# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.bank_schema import BankSchema
from artifactsmmo import util


class BankResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: BankSchema=None):
        """BankResponseSchema - a model defined in OpenAPI

        :param data: The data of this BankResponseSchema.
        """
        self.openapi_types = {
            'data': BankSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BankResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BankResponseSchema of this BankResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this BankResponseSchema.


        :return: The data of this BankResponseSchema.
        :rtype: BankSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this BankResponseSchema.


        :param data: The data of this BankResponseSchema.
        :type data: BankSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
