# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.bank_gold_transaction_schema import BankGoldTransactionSchema
from artifactsmmo import util


class BankGoldTransactionResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: BankGoldTransactionSchema=None):
        """BankGoldTransactionResponseSchema - a model defined in OpenAPI

        :param data: The data of this BankGoldTransactionResponseSchema.
        """
        self.openapi_types = {
            'data': BankGoldTransactionSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'BankGoldTransactionResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The BankGoldTransactionResponseSchema of this BankGoldTransactionResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this BankGoldTransactionResponseSchema.


        :return: The data of this BankGoldTransactionResponseSchema.
        :rtype: BankGoldTransactionSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this BankGoldTransactionResponseSchema.


        :param data: The data of this BankGoldTransactionResponseSchema.
        :type data: BankGoldTransactionSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
