# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_fight_schema import CharacterFightSchema
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo import util


class CharacterFightDataSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, fight: CharacterFightSchema=None, characters: List[CharacterSchema]=None):
        """CharacterFightDataSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this CharacterFightDataSchema.
        :param fight: The fight of this CharacterFightDataSchema.
        :param characters: The characters of this CharacterFightDataSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'fight': CharacterFightSchema,
            'characters': List[CharacterSchema]
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'fight': 'fight',
            'characters': 'characters'
        }

        self._cooldown = cooldown
        self._fight = fight
        self._characters = characters

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterFightDataSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterFightDataSchema of this CharacterFightDataSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this CharacterFightDataSchema.

        Cooldown details.

        :return: The cooldown of this CharacterFightDataSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this CharacterFightDataSchema.

        Cooldown details.

        :param cooldown: The cooldown of this CharacterFightDataSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def fight(self):
        """Gets the fight of this CharacterFightDataSchema.

        Character fight details.

        :return: The fight of this CharacterFightDataSchema.
        :rtype: CharacterFightSchema
        """
        return self._fight

    @fight.setter
    def fight(self, fight):
        """Sets the fight of this CharacterFightDataSchema.

        Character fight details.

        :param fight: The fight of this CharacterFightDataSchema.
        :type fight: CharacterFightSchema
        """
        if fight is None:
            raise ValueError("Invalid value for `fight`, must not be `None`")

        self._fight = fight

    @property
    def characters(self):
        """Gets the characters of this CharacterFightDataSchema.

        All characters involved.

        :return: The characters of this CharacterFightDataSchema.
        :rtype: List[CharacterSchema]
        """
        return self._characters

    @characters.setter
    def characters(self, characters):
        """Sets the characters of this CharacterFightDataSchema.

        All characters involved.

        :param characters: The characters of this CharacterFightDataSchema.
        :type characters: List[CharacterSchema]
        """
        if characters is None:
            raise ValueError("Invalid value for `characters`, must not be `None`")

        self._characters = characters
