# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class CharacterLeaderboardType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    COMBAT = 'combat'
    WOODCUTTING = 'woodcutting'
    MINING = 'mining'
    FISHING = 'fishing'
    WEAPONCRAFTING = 'weaponcrafting'
    GEARCRAFTING = 'gearcrafting'
    JEWELRYCRAFTING = 'jewelrycrafting'
    COOKING = 'cooking'
    ALCHEMY = 'alchemy'

    def __init__(self):
        """CharacterLeaderboardType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterLeaderboardType':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterLeaderboardType of this CharacterLeaderboardType.
        """
        return util.deserialize_model(dikt, cls)
