# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo import util


class CharacterResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: CharacterSchema=None):
        """CharacterResponseSchema - a model defined in OpenAPI

        :param data: The data of this CharacterResponseSchema.
        """
        self.openapi_types = {
            'data': CharacterSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterResponseSchema of this CharacterResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CharacterResponseSchema.


        :return: The data of this CharacterResponseSchema.
        :rtype: CharacterSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CharacterResponseSchema.


        :param data: The data of this CharacterResponseSchema.
        :type data: CharacterSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
