# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_fight_data_schema import CharacterFightDataSchema
from artifactsmmo import util


class CharacterFightResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: CharacterFightDataSchema=None):
        """CharacterFightResponseSchema - a model defined in OpenAPI

        :param data: The data of this CharacterFightResponseSchema.
        """
        self.openapi_types = {
            'data': CharacterFightDataSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterFightResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterFightResponseSchema of this CharacterFightResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CharacterFightResponseSchema.


        :return: The data of this CharacterFightResponseSchema.
        :rtype: CharacterFightDataSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CharacterFightResponseSchema.


        :param data: The data of this CharacterFightResponseSchema.
        :type data: CharacterFightDataSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
