# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_multi_fight_result_schema import CharacterMultiFightResultSchema
from artifactsmmo.models.fight_result import FightResult
from artifactsmmo import util


class CharacterFightSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result: FightResult=None, turns: int=None, opponent: str=None, logs: List[str]=None, characters: List[CharacterMultiFightResultSchema]=None):
        """CharacterFightSchema - a model defined in OpenAPI

        :param result: The result of this CharacterFightSchema.
        :param turns: The turns of this CharacterFightSchema.
        :param opponent: The opponent of this CharacterFightSchema.
        :param logs: The logs of this CharacterFightSchema.
        :param characters: The characters of this CharacterFightSchema.
        """
        self.openapi_types = {
            'result': FightResult,
            'turns': int,
            'opponent': str,
            'logs': List[str],
            'characters': List[CharacterMultiFightResultSchema]
        }

        self.attribute_map = {
            'result': 'result',
            'turns': 'turns',
            'opponent': 'opponent',
            'logs': 'logs',
            'characters': 'characters'
        }

        self._result = result
        self._turns = turns
        self._opponent = opponent
        self._logs = logs
        self._characters = characters

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterFightSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterFightSchema of this CharacterFightSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self):
        """Gets the result of this CharacterFightSchema.

        The result of the fight.

        :return: The result of this CharacterFightSchema.
        :rtype: FightResult
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this CharacterFightSchema.

        The result of the fight.

        :param result: The result of this CharacterFightSchema.
        :type result: FightResult
        """
        if result is None:
            raise ValueError("Invalid value for `result`, must not be `None`")

        self._result = result

    @property
    def turns(self):
        """Gets the turns of this CharacterFightSchema.

        Numbers of the turns of the combat.

        :return: The turns of this CharacterFightSchema.
        :rtype: int
        """
        return self._turns

    @turns.setter
    def turns(self, turns):
        """Sets the turns of this CharacterFightSchema.

        Numbers of the turns of the combat.

        :param turns: The turns of this CharacterFightSchema.
        :type turns: int
        """
        if turns is None:
            raise ValueError("Invalid value for `turns`, must not be `None`")

        self._turns = turns

    @property
    def opponent(self):
        """Gets the opponent of this CharacterFightSchema.

        The code of the monster fought.

        :return: The opponent of this CharacterFightSchema.
        :rtype: str
        """
        return self._opponent

    @opponent.setter
    def opponent(self, opponent):
        """Sets the opponent of this CharacterFightSchema.

        The code of the monster fought.

        :param opponent: The opponent of this CharacterFightSchema.
        :type opponent: str
        """
        if opponent is None:
            raise ValueError("Invalid value for `opponent`, must not be `None`")

        self._opponent = opponent

    @property
    def logs(self):
        """Gets the logs of this CharacterFightSchema.

        The fight logs.

        :return: The logs of this CharacterFightSchema.
        :rtype: List[str]
        """
        return self._logs

    @logs.setter
    def logs(self, logs):
        """Sets the logs of this CharacterFightSchema.

        The fight logs.

        :param logs: The logs of this CharacterFightSchema.
        :type logs: List[str]
        """
        if logs is None:
            raise ValueError("Invalid value for `logs`, must not be `None`")

        self._logs = logs

    @property
    def characters(self):
        """Gets the characters of this CharacterFightSchema.

        Results for each character.

        :return: The characters of this CharacterFightSchema.
        :rtype: List[CharacterMultiFightResultSchema]
        """
        return self._characters

    @characters.setter
    def characters(self, characters):
        """Sets the characters of this CharacterFightSchema.

        Results for each character.

        :param characters: The characters of this CharacterFightSchema.
        :type characters: List[CharacterMultiFightResultSchema]
        """
        if characters is None:
            raise ValueError("Invalid value for `characters`, must not be `None`")

        self._characters = characters
