# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_rest_data_schema import CharacterRestDataSchema
from artifactsmmo import util


class CharacterRestResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: CharacterRestDataSchema=None):
        """CharacterRestResponseSchema - a model defined in OpenAPI

        :param data: The data of this CharacterRestResponseSchema.
        """
        self.openapi_types = {
            'data': CharacterRestDataSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterRestResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterRestResponseSchema of this CharacterRestResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CharacterRestResponseSchema.


        :return: The data of this CharacterRestResponseSchema.
        :rtype: CharacterRestDataSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CharacterRestResponseSchema.


        :param data: The data of this CharacterRestResponseSchema.
        :type data: CharacterRestDataSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
