# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_transition_data_schema import CharacterTransitionDataSchema
from artifactsmmo import util


class CharacterTransitionResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: CharacterTransitionDataSchema=None):
        """CharacterTransitionResponseSchema - a model defined in OpenAPI

        :param data: The data of this CharacterTransitionResponseSchema.
        """
        self.openapi_types = {
            'data': CharacterTransitionDataSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterTransitionResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterTransitionResponseSchema of this CharacterTransitionResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CharacterTransitionResponseSchema.


        :return: The data of this CharacterTransitionResponseSchema.
        :rtype: CharacterTransitionDataSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CharacterTransitionResponseSchema.


        :param data: The data of this CharacterTransitionResponseSchema.
        :type data: CharacterTransitionDataSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
