# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo.models.map_schema import MapSchema
from artifactsmmo import util


class CharacterMovementDataSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, destination: MapSchema=None, path: List[List[object]]=None, character: CharacterSchema=None):
        """CharacterMovementDataSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this CharacterMovementDataSchema.
        :param destination: The destination of this CharacterMovementDataSchema.
        :param path: The path of this CharacterMovementDataSchema.
        :param character: The character of this CharacterMovementDataSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'destination': MapSchema,
            'path': List[List[object]],
            'character': CharacterSchema
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'destination': 'destination',
            'path': 'path',
            'character': 'character'
        }

        self._cooldown = cooldown
        self._destination = destination
        self._path = path
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterMovementDataSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterMovementDataSchema of this CharacterMovementDataSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this CharacterMovementDataSchema.

        Cooldown details

        :return: The cooldown of this CharacterMovementDataSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this CharacterMovementDataSchema.

        Cooldown details

        :param cooldown: The cooldown of this CharacterMovementDataSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def destination(self):
        """Gets the destination of this CharacterMovementDataSchema.

        Destination details.

        :return: The destination of this CharacterMovementDataSchema.
        :rtype: MapSchema
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this CharacterMovementDataSchema.

        Destination details.

        :param destination: The destination of this CharacterMovementDataSchema.
        :type destination: MapSchema
        """
        if destination is None:
            raise ValueError("Invalid value for `destination`, must not be `None`")

        self._destination = destination

    @property
    def path(self):
        """Gets the path of this CharacterMovementDataSchema.

        Path taken from start to destination (list of coordinates)

        :return: The path of this CharacterMovementDataSchema.
        :rtype: List[List[object]]
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this CharacterMovementDataSchema.

        Path taken from start to destination (list of coordinates)

        :param path: The path of this CharacterMovementDataSchema.
        :type path: List[List[object]]
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")

        self._path = path

    @property
    def character(self):
        """Gets the character of this CharacterMovementDataSchema.

        Character details.

        :return: The character of this CharacterMovementDataSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this CharacterMovementDataSchema.

        Character details.

        :param character: The character of this CharacterMovementDataSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
