# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo import util


class CharactersListSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: List[CharacterSchema]=None):
        """CharactersListSchema - a model defined in OpenAPI

        :param data: The data of this CharactersListSchema.
        """
        self.openapi_types = {
            'data': List[CharacterSchema]
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharactersListSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharactersListSchema of this CharactersListSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CharactersListSchema.

        List of your characters.

        :return: The data of this CharactersListSchema.
        :rtype: List[CharacterSchema]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CharactersListSchema.

        List of your characters.

        :param data: The data of this CharactersListSchema.
        :type data: List[CharacterSchema]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
