# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo import util


class CharacterRestDataSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, hp_restored: int=None, character: CharacterSchema=None):
        """CharacterRestDataSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this CharacterRestDataSchema.
        :param hp_restored: The hp_restored of this CharacterRestDataSchema.
        :param character: The character of this CharacterRestDataSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'hp_restored': int,
            'character': CharacterSchema
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'hp_restored': 'hp_restored',
            'character': 'character'
        }

        self._cooldown = cooldown
        self._hp_restored = hp_restored
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterRestDataSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterRestDataSchema of this CharacterRestDataSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this CharacterRestDataSchema.

        Cooldown details

        :return: The cooldown of this CharacterRestDataSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this CharacterRestDataSchema.

        Cooldown details

        :param cooldown: The cooldown of this CharacterRestDataSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def hp_restored(self):
        """Gets the hp_restored of this CharacterRestDataSchema.

        The amount of HP restored.

        :return: The hp_restored of this CharacterRestDataSchema.
        :rtype: int
        """
        return self._hp_restored

    @hp_restored.setter
    def hp_restored(self, hp_restored):
        """Sets the hp_restored of this CharacterRestDataSchema.

        The amount of HP restored.

        :param hp_restored: The hp_restored of this CharacterRestDataSchema.
        :type hp_restored: int
        """
        if hp_restored is None:
            raise ValueError("Invalid value for `hp_restored`, must not be `None`")

        self._hp_restored = hp_restored

    @property
    def character(self):
        """Gets the character of this CharacterRestDataSchema.

        Character details.

        :return: The character of this CharacterRestDataSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this CharacterRestDataSchema.

        Character details.

        :param character: The character of this CharacterRestDataSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
