# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.account_status import AccountStatus
from artifactsmmo import util


class CharacterLeaderboardSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, position: int=None, name: str=None, account: str=None, status: AccountStatus=None, skin: str=None, level: int=None, total_xp: int=None, mining_level: int=None, mining_total_xp: int=None, woodcutting_level: int=None, woodcutting_total_xp: int=None, fishing_level: int=None, fishing_total_xp: int=None, weaponcrafting_level: int=None, weaponcrafting_total_xp: int=None, gearcrafting_level: int=None, gearcrafting_total_xp: int=None, jewelrycrafting_level: int=None, jewelrycrafting_total_xp: int=None, cooking_level: int=None, cooking_total_xp: int=None, alchemy_level: int=None, alchemy_total_xp: int=None, gold: int=None):
        """CharacterLeaderboardSchema - a model defined in OpenAPI

        :param position: The position of this CharacterLeaderboardSchema.
        :param name: The name of this CharacterLeaderboardSchema.
        :param account: The account of this CharacterLeaderboardSchema.
        :param status: The status of this CharacterLeaderboardSchema.
        :param skin: The skin of this CharacterLeaderboardSchema.
        :param level: The level of this CharacterLeaderboardSchema.
        :param total_xp: The total_xp of this CharacterLeaderboardSchema.
        :param mining_level: The mining_level of this CharacterLeaderboardSchema.
        :param mining_total_xp: The mining_total_xp of this CharacterLeaderboardSchema.
        :param woodcutting_level: The woodcutting_level of this CharacterLeaderboardSchema.
        :param woodcutting_total_xp: The woodcutting_total_xp of this CharacterLeaderboardSchema.
        :param fishing_level: The fishing_level of this CharacterLeaderboardSchema.
        :param fishing_total_xp: The fishing_total_xp of this CharacterLeaderboardSchema.
        :param weaponcrafting_level: The weaponcrafting_level of this CharacterLeaderboardSchema.
        :param weaponcrafting_total_xp: The weaponcrafting_total_xp of this CharacterLeaderboardSchema.
        :param gearcrafting_level: The gearcrafting_level of this CharacterLeaderboardSchema.
        :param gearcrafting_total_xp: The gearcrafting_total_xp of this CharacterLeaderboardSchema.
        :param jewelrycrafting_level: The jewelrycrafting_level of this CharacterLeaderboardSchema.
        :param jewelrycrafting_total_xp: The jewelrycrafting_total_xp of this CharacterLeaderboardSchema.
        :param cooking_level: The cooking_level of this CharacterLeaderboardSchema.
        :param cooking_total_xp: The cooking_total_xp of this CharacterLeaderboardSchema.
        :param alchemy_level: The alchemy_level of this CharacterLeaderboardSchema.
        :param alchemy_total_xp: The alchemy_total_xp of this CharacterLeaderboardSchema.
        :param gold: The gold of this CharacterLeaderboardSchema.
        """
        self.openapi_types = {
            'position': int,
            'name': str,
            'account': str,
            'status': AccountStatus,
            'skin': str,
            'level': int,
            'total_xp': int,
            'mining_level': int,
            'mining_total_xp': int,
            'woodcutting_level': int,
            'woodcutting_total_xp': int,
            'fishing_level': int,
            'fishing_total_xp': int,
            'weaponcrafting_level': int,
            'weaponcrafting_total_xp': int,
            'gearcrafting_level': int,
            'gearcrafting_total_xp': int,
            'jewelrycrafting_level': int,
            'jewelrycrafting_total_xp': int,
            'cooking_level': int,
            'cooking_total_xp': int,
            'alchemy_level': int,
            'alchemy_total_xp': int,
            'gold': int
        }

        self.attribute_map = {
            'position': 'position',
            'name': 'name',
            'account': 'account',
            'status': 'status',
            'skin': 'skin',
            'level': 'level',
            'total_xp': 'total_xp',
            'mining_level': 'mining_level',
            'mining_total_xp': 'mining_total_xp',
            'woodcutting_level': 'woodcutting_level',
            'woodcutting_total_xp': 'woodcutting_total_xp',
            'fishing_level': 'fishing_level',
            'fishing_total_xp': 'fishing_total_xp',
            'weaponcrafting_level': 'weaponcrafting_level',
            'weaponcrafting_total_xp': 'weaponcrafting_total_xp',
            'gearcrafting_level': 'gearcrafting_level',
            'gearcrafting_total_xp': 'gearcrafting_total_xp',
            'jewelrycrafting_level': 'jewelrycrafting_level',
            'jewelrycrafting_total_xp': 'jewelrycrafting_total_xp',
            'cooking_level': 'cooking_level',
            'cooking_total_xp': 'cooking_total_xp',
            'alchemy_level': 'alchemy_level',
            'alchemy_total_xp': 'alchemy_total_xp',
            'gold': 'gold'
        }

        self._position = position
        self._name = name
        self._account = account
        self._status = status
        self._skin = skin
        self._level = level
        self._total_xp = total_xp
        self._mining_level = mining_level
        self._mining_total_xp = mining_total_xp
        self._woodcutting_level = woodcutting_level
        self._woodcutting_total_xp = woodcutting_total_xp
        self._fishing_level = fishing_level
        self._fishing_total_xp = fishing_total_xp
        self._weaponcrafting_level = weaponcrafting_level
        self._weaponcrafting_total_xp = weaponcrafting_total_xp
        self._gearcrafting_level = gearcrafting_level
        self._gearcrafting_total_xp = gearcrafting_total_xp
        self._jewelrycrafting_level = jewelrycrafting_level
        self._jewelrycrafting_total_xp = jewelrycrafting_total_xp
        self._cooking_level = cooking_level
        self._cooking_total_xp = cooking_total_xp
        self._alchemy_level = alchemy_level
        self._alchemy_total_xp = alchemy_total_xp
        self._gold = gold

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterLeaderboardSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterLeaderboardSchema of this CharacterLeaderboardSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def position(self):
        """Gets the position of this CharacterLeaderboardSchema.

        Position in the leaderboard.

        :return: The position of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this CharacterLeaderboardSchema.

        Position in the leaderboard.

        :param position: The position of this CharacterLeaderboardSchema.
        :type position: int
        """
        if position is None:
            raise ValueError("Invalid value for `position`, must not be `None`")

        self._position = position

    @property
    def name(self):
        """Gets the name of this CharacterLeaderboardSchema.

        Character name.

        :return: The name of this CharacterLeaderboardSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CharacterLeaderboardSchema.

        Character name.

        :param name: The name of this CharacterLeaderboardSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def account(self):
        """Gets the account of this CharacterLeaderboardSchema.

        Account name.

        :return: The account of this CharacterLeaderboardSchema.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this CharacterLeaderboardSchema.

        Account name.

        :param account: The account of this CharacterLeaderboardSchema.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")

        self._account = account

    @property
    def status(self):
        """Gets the status of this CharacterLeaderboardSchema.

        Member status.

        :return: The status of this CharacterLeaderboardSchema.
        :rtype: AccountStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CharacterLeaderboardSchema.

        Member status.

        :param status: The status of this CharacterLeaderboardSchema.
        :type status: AccountStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")

        self._status = status

    @property
    def skin(self):
        """Gets the skin of this CharacterLeaderboardSchema.

        Character skin code.

        :return: The skin of this CharacterLeaderboardSchema.
        :rtype: str
        """
        return self._skin

    @skin.setter
    def skin(self, skin):
        """Sets the skin of this CharacterLeaderboardSchema.

        Character skin code.

        :param skin: The skin of this CharacterLeaderboardSchema.
        :type skin: str
        """
        if skin is None:
            raise ValueError("Invalid value for `skin`, must not be `None`")

        self._skin = skin

    @property
    def level(self):
        """Gets the level of this CharacterLeaderboardSchema.

        Combat level.

        :return: The level of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this CharacterLeaderboardSchema.

        Combat level.

        :param level: The level of this CharacterLeaderboardSchema.
        :type level: int
        """
        if level is None:
            raise ValueError("Invalid value for `level`, must not be `None`")

        self._level = level

    @property
    def total_xp(self):
        """Gets the total_xp of this CharacterLeaderboardSchema.

        Total XP of your character.

        :return: The total_xp of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._total_xp

    @total_xp.setter
    def total_xp(self, total_xp):
        """Sets the total_xp of this CharacterLeaderboardSchema.

        Total XP of your character.

        :param total_xp: The total_xp of this CharacterLeaderboardSchema.
        :type total_xp: int
        """
        if total_xp is None:
            raise ValueError("Invalid value for `total_xp`, must not be `None`")

        self._total_xp = total_xp

    @property
    def mining_level(self):
        """Gets the mining_level of this CharacterLeaderboardSchema.

        Mining level.

        :return: The mining_level of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._mining_level

    @mining_level.setter
    def mining_level(self, mining_level):
        """Sets the mining_level of this CharacterLeaderboardSchema.

        Mining level.

        :param mining_level: The mining_level of this CharacterLeaderboardSchema.
        :type mining_level: int
        """
        if mining_level is None:
            raise ValueError("Invalid value for `mining_level`, must not be `None`")

        self._mining_level = mining_level

    @property
    def mining_total_xp(self):
        """Gets the mining_total_xp of this CharacterLeaderboardSchema.

        Mining total xp.

        :return: The mining_total_xp of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._mining_total_xp

    @mining_total_xp.setter
    def mining_total_xp(self, mining_total_xp):
        """Sets the mining_total_xp of this CharacterLeaderboardSchema.

        Mining total xp.

        :param mining_total_xp: The mining_total_xp of this CharacterLeaderboardSchema.
        :type mining_total_xp: int
        """
        if mining_total_xp is None:
            raise ValueError("Invalid value for `mining_total_xp`, must not be `None`")

        self._mining_total_xp = mining_total_xp

    @property
    def woodcutting_level(self):
        """Gets the woodcutting_level of this CharacterLeaderboardSchema.

        Woodcutting level.

        :return: The woodcutting_level of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._woodcutting_level

    @woodcutting_level.setter
    def woodcutting_level(self, woodcutting_level):
        """Sets the woodcutting_level of this CharacterLeaderboardSchema.

        Woodcutting level.

        :param woodcutting_level: The woodcutting_level of this CharacterLeaderboardSchema.
        :type woodcutting_level: int
        """
        if woodcutting_level is None:
            raise ValueError("Invalid value for `woodcutting_level`, must not be `None`")

        self._woodcutting_level = woodcutting_level

    @property
    def woodcutting_total_xp(self):
        """Gets the woodcutting_total_xp of this CharacterLeaderboardSchema.

        Woodcutting total xp.

        :return: The woodcutting_total_xp of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._woodcutting_total_xp

    @woodcutting_total_xp.setter
    def woodcutting_total_xp(self, woodcutting_total_xp):
        """Sets the woodcutting_total_xp of this CharacterLeaderboardSchema.

        Woodcutting total xp.

        :param woodcutting_total_xp: The woodcutting_total_xp of this CharacterLeaderboardSchema.
        :type woodcutting_total_xp: int
        """
        if woodcutting_total_xp is None:
            raise ValueError("Invalid value for `woodcutting_total_xp`, must not be `None`")

        self._woodcutting_total_xp = woodcutting_total_xp

    @property
    def fishing_level(self):
        """Gets the fishing_level of this CharacterLeaderboardSchema.

        Fishing level.

        :return: The fishing_level of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._fishing_level

    @fishing_level.setter
    def fishing_level(self, fishing_level):
        """Sets the fishing_level of this CharacterLeaderboardSchema.

        Fishing level.

        :param fishing_level: The fishing_level of this CharacterLeaderboardSchema.
        :type fishing_level: int
        """
        if fishing_level is None:
            raise ValueError("Invalid value for `fishing_level`, must not be `None`")

        self._fishing_level = fishing_level

    @property
    def fishing_total_xp(self):
        """Gets the fishing_total_xp of this CharacterLeaderboardSchema.

        Fishing total xp.

        :return: The fishing_total_xp of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._fishing_total_xp

    @fishing_total_xp.setter
    def fishing_total_xp(self, fishing_total_xp):
        """Sets the fishing_total_xp of this CharacterLeaderboardSchema.

        Fishing total xp.

        :param fishing_total_xp: The fishing_total_xp of this CharacterLeaderboardSchema.
        :type fishing_total_xp: int
        """
        if fishing_total_xp is None:
            raise ValueError("Invalid value for `fishing_total_xp`, must not be `None`")

        self._fishing_total_xp = fishing_total_xp

    @property
    def weaponcrafting_level(self):
        """Gets the weaponcrafting_level of this CharacterLeaderboardSchema.

        Weaponcrafting level.

        :return: The weaponcrafting_level of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._weaponcrafting_level

    @weaponcrafting_level.setter
    def weaponcrafting_level(self, weaponcrafting_level):
        """Sets the weaponcrafting_level of this CharacterLeaderboardSchema.

        Weaponcrafting level.

        :param weaponcrafting_level: The weaponcrafting_level of this CharacterLeaderboardSchema.
        :type weaponcrafting_level: int
        """
        if weaponcrafting_level is None:
            raise ValueError("Invalid value for `weaponcrafting_level`, must not be `None`")

        self._weaponcrafting_level = weaponcrafting_level

    @property
    def weaponcrafting_total_xp(self):
        """Gets the weaponcrafting_total_xp of this CharacterLeaderboardSchema.

        Weaponcrafting total xp.

        :return: The weaponcrafting_total_xp of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._weaponcrafting_total_xp

    @weaponcrafting_total_xp.setter
    def weaponcrafting_total_xp(self, weaponcrafting_total_xp):
        """Sets the weaponcrafting_total_xp of this CharacterLeaderboardSchema.

        Weaponcrafting total xp.

        :param weaponcrafting_total_xp: The weaponcrafting_total_xp of this CharacterLeaderboardSchema.
        :type weaponcrafting_total_xp: int
        """
        if weaponcrafting_total_xp is None:
            raise ValueError("Invalid value for `weaponcrafting_total_xp`, must not be `None`")

        self._weaponcrafting_total_xp = weaponcrafting_total_xp

    @property
    def gearcrafting_level(self):
        """Gets the gearcrafting_level of this CharacterLeaderboardSchema.

        Gearcrafting level.

        :return: The gearcrafting_level of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._gearcrafting_level

    @gearcrafting_level.setter
    def gearcrafting_level(self, gearcrafting_level):
        """Sets the gearcrafting_level of this CharacterLeaderboardSchema.

        Gearcrafting level.

        :param gearcrafting_level: The gearcrafting_level of this CharacterLeaderboardSchema.
        :type gearcrafting_level: int
        """
        if gearcrafting_level is None:
            raise ValueError("Invalid value for `gearcrafting_level`, must not be `None`")

        self._gearcrafting_level = gearcrafting_level

    @property
    def gearcrafting_total_xp(self):
        """Gets the gearcrafting_total_xp of this CharacterLeaderboardSchema.

        Gearcrafting total xp.

        :return: The gearcrafting_total_xp of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._gearcrafting_total_xp

    @gearcrafting_total_xp.setter
    def gearcrafting_total_xp(self, gearcrafting_total_xp):
        """Sets the gearcrafting_total_xp of this CharacterLeaderboardSchema.

        Gearcrafting total xp.

        :param gearcrafting_total_xp: The gearcrafting_total_xp of this CharacterLeaderboardSchema.
        :type gearcrafting_total_xp: int
        """
        if gearcrafting_total_xp is None:
            raise ValueError("Invalid value for `gearcrafting_total_xp`, must not be `None`")

        self._gearcrafting_total_xp = gearcrafting_total_xp

    @property
    def jewelrycrafting_level(self):
        """Gets the jewelrycrafting_level of this CharacterLeaderboardSchema.

        Jewelrycrafting level.

        :return: The jewelrycrafting_level of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._jewelrycrafting_level

    @jewelrycrafting_level.setter
    def jewelrycrafting_level(self, jewelrycrafting_level):
        """Sets the jewelrycrafting_level of this CharacterLeaderboardSchema.

        Jewelrycrafting level.

        :param jewelrycrafting_level: The jewelrycrafting_level of this CharacterLeaderboardSchema.
        :type jewelrycrafting_level: int
        """
        if jewelrycrafting_level is None:
            raise ValueError("Invalid value for `jewelrycrafting_level`, must not be `None`")

        self._jewelrycrafting_level = jewelrycrafting_level

    @property
    def jewelrycrafting_total_xp(self):
        """Gets the jewelrycrafting_total_xp of this CharacterLeaderboardSchema.

        Jewelrycrafting total xp.

        :return: The jewelrycrafting_total_xp of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._jewelrycrafting_total_xp

    @jewelrycrafting_total_xp.setter
    def jewelrycrafting_total_xp(self, jewelrycrafting_total_xp):
        """Sets the jewelrycrafting_total_xp of this CharacterLeaderboardSchema.

        Jewelrycrafting total xp.

        :param jewelrycrafting_total_xp: The jewelrycrafting_total_xp of this CharacterLeaderboardSchema.
        :type jewelrycrafting_total_xp: int
        """
        if jewelrycrafting_total_xp is None:
            raise ValueError("Invalid value for `jewelrycrafting_total_xp`, must not be `None`")

        self._jewelrycrafting_total_xp = jewelrycrafting_total_xp

    @property
    def cooking_level(self):
        """Gets the cooking_level of this CharacterLeaderboardSchema.

        Cooking level.

        :return: The cooking_level of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._cooking_level

    @cooking_level.setter
    def cooking_level(self, cooking_level):
        """Sets the cooking_level of this CharacterLeaderboardSchema.

        Cooking level.

        :param cooking_level: The cooking_level of this CharacterLeaderboardSchema.
        :type cooking_level: int
        """
        if cooking_level is None:
            raise ValueError("Invalid value for `cooking_level`, must not be `None`")

        self._cooking_level = cooking_level

    @property
    def cooking_total_xp(self):
        """Gets the cooking_total_xp of this CharacterLeaderboardSchema.

        Cooking total xp.

        :return: The cooking_total_xp of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._cooking_total_xp

    @cooking_total_xp.setter
    def cooking_total_xp(self, cooking_total_xp):
        """Sets the cooking_total_xp of this CharacterLeaderboardSchema.

        Cooking total xp.

        :param cooking_total_xp: The cooking_total_xp of this CharacterLeaderboardSchema.
        :type cooking_total_xp: int
        """
        if cooking_total_xp is None:
            raise ValueError("Invalid value for `cooking_total_xp`, must not be `None`")

        self._cooking_total_xp = cooking_total_xp

    @property
    def alchemy_level(self):
        """Gets the alchemy_level of this CharacterLeaderboardSchema.

        Alchemy level.

        :return: The alchemy_level of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._alchemy_level

    @alchemy_level.setter
    def alchemy_level(self, alchemy_level):
        """Sets the alchemy_level of this CharacterLeaderboardSchema.

        Alchemy level.

        :param alchemy_level: The alchemy_level of this CharacterLeaderboardSchema.
        :type alchemy_level: int
        """
        if alchemy_level is None:
            raise ValueError("Invalid value for `alchemy_level`, must not be `None`")

        self._alchemy_level = alchemy_level

    @property
    def alchemy_total_xp(self):
        """Gets the alchemy_total_xp of this CharacterLeaderboardSchema.

        Alchemy total xp.

        :return: The alchemy_total_xp of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._alchemy_total_xp

    @alchemy_total_xp.setter
    def alchemy_total_xp(self, alchemy_total_xp):
        """Sets the alchemy_total_xp of this CharacterLeaderboardSchema.

        Alchemy total xp.

        :param alchemy_total_xp: The alchemy_total_xp of this CharacterLeaderboardSchema.
        :type alchemy_total_xp: int
        """
        if alchemy_total_xp is None:
            raise ValueError("Invalid value for `alchemy_total_xp`, must not be `None`")

        self._alchemy_total_xp = alchemy_total_xp

    @property
    def gold(self):
        """Gets the gold of this CharacterLeaderboardSchema.

        The numbers of gold on this character.

        :return: The gold of this CharacterLeaderboardSchema.
        :rtype: int
        """
        return self._gold

    @gold.setter
    def gold(self, gold):
        """Sets the gold of this CharacterLeaderboardSchema.

        The numbers of gold on this character.

        :param gold: The gold of this CharacterLeaderboardSchema.
        :type gold: int
        """
        if gold is None:
            raise ValueError("Invalid value for `gold`, must not be `None`")

        self._gold = gold
