# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_movement_data_schema import CharacterMovementDataSchema
from artifactsmmo import util


class CharacterMovementResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: CharacterMovementDataSchema=None):
        """CharacterMovementResponseSchema - a model defined in OpenAPI

        :param data: The data of this CharacterMovementResponseSchema.
        """
        self.openapi_types = {
            'data': CharacterMovementDataSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CharacterMovementResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CharacterMovementResponseSchema of this CharacterMovementResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this CharacterMovementResponseSchema.


        :return: The data of this CharacterMovementResponseSchema.
        :rtype: CharacterMovementDataSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CharacterMovementResponseSchema.


        :param data: The data of this CharacterMovementResponseSchema.
        :type data: CharacterMovementDataSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
