# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.claim_pending_item_data_schema import ClaimPendingItemDataSchema
from artifactsmmo import util


class ClaimPendingItemResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: ClaimPendingItemDataSchema=None):
        """ClaimPendingItemResponseSchema - a model defined in OpenAPI

        :param data: The data of this ClaimPendingItemResponseSchema.
        """
        self.openapi_types = {
            'data': ClaimPendingItemDataSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ClaimPendingItemResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ClaimPendingItemResponseSchema of this ClaimPendingItemResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ClaimPendingItemResponseSchema.

        Response data containing cooldown, item, and character.

        :return: The data of this ClaimPendingItemResponseSchema.
        :rtype: ClaimPendingItemDataSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ClaimPendingItemResponseSchema.

        Response data containing cooldown, item, and character.

        :param data: The data of this ClaimPendingItemResponseSchema.
        :type data: ClaimPendingItemDataSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
