# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.fake_character_schema import FakeCharacterSchema
import re
from artifactsmmo import util


class CombatSimulationRequestSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, characters: List[FakeCharacterSchema]=None, monster: str=None, iterations: int=None):
        """CombatSimulationRequestSchema - a model defined in OpenAPI

        :param characters: The characters of this CombatSimulationRequestSchema.
        :param monster: The monster of this CombatSimulationRequestSchema.
        :param iterations: The iterations of this CombatSimulationRequestSchema.
        """
        self.openapi_types = {
            'characters': List[FakeCharacterSchema],
            'monster': str,
            'iterations': int
        }

        self.attribute_map = {
            'characters': 'characters',
            'monster': 'monster',
            'iterations': 'iterations'
        }

        self._characters = characters
        self._monster = monster
        self._iterations = iterations

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CombatSimulationRequestSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The CombatSimulationRequestSchema of this CombatSimulationRequestSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def characters(self):
        """Gets the characters of this CombatSimulationRequestSchema.

        List of fake characters (1-3).

        :return: The characters of this CombatSimulationRequestSchema.
        :rtype: List[FakeCharacterSchema]
        """
        return self._characters

    @characters.setter
    def characters(self, characters):
        """Sets the characters of this CombatSimulationRequestSchema.

        List of fake characters (1-3).

        :param characters: The characters of this CombatSimulationRequestSchema.
        :type characters: List[FakeCharacterSchema]
        """
        if characters is None:
            raise ValueError("Invalid value for `characters`, must not be `None`")
        if characters is not None and len(characters) > 3:
            raise ValueError("Invalid value for `characters`, number of items must be less than or equal to `3`")
        if characters is not None and len(characters) < 1:
            raise ValueError("Invalid value for `characters`, number of items must be greater than or equal to `1`")

        self._characters = characters

    @property
    def monster(self):
        """Gets the monster of this CombatSimulationRequestSchema.

        Monster code to fight against.

        :return: The monster of this CombatSimulationRequestSchema.
        :rtype: str
        """
        return self._monster

    @monster.setter
    def monster(self, monster):
        """Sets the monster of this CombatSimulationRequestSchema.

        Monster code to fight against.

        :param monster: The monster of this CombatSimulationRequestSchema.
        :type monster: str
        """
        if monster is None:
            raise ValueError("Invalid value for `monster`, must not be `None`")
        if monster is not None and not re.search(r'^[a-zA-Z0-9_-]+$', monster):
            raise ValueError("Invalid value for `monster`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._monster = monster

    @property
    def iterations(self):
        """Gets the iterations of this CombatSimulationRequestSchema.

        Number of combat iterations to simulate.

        :return: The iterations of this CombatSimulationRequestSchema.
        :rtype: int
        """
        return self._iterations

    @iterations.setter
    def iterations(self, iterations):
        """Sets the iterations of this CombatSimulationRequestSchema.

        Number of combat iterations to simulate.

        :param iterations: The iterations of this CombatSimulationRequestSchema.
        :type iterations: int
        """
        if iterations is None:
            raise ValueError("Invalid value for `iterations`, must not be `None`")
        if iterations is not None and iterations > 100:
            raise ValueError("Invalid value for `iterations`, must be a value less than or equal to `100`")
        if iterations is not None and iterations < 1:
            raise ValueError("Invalid value for `iterations`, must be a value greater than or equal to `1`")

        self._iterations = iterations
