# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.item_schema import ItemSchema
from artifactsmmo import util


class DataPageItemSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: List[ItemSchema]=None, total: int=None, page: int=None, size: int=None, pages: int=None):
        """DataPageItemSchema - a model defined in OpenAPI

        :param data: The data of this DataPageItemSchema.
        :param total: The total of this DataPageItemSchema.
        :param page: The page of this DataPageItemSchema.
        :param size: The size of this DataPageItemSchema.
        :param pages: The pages of this DataPageItemSchema.
        """
        self.openapi_types = {
            'data': List[ItemSchema],
            'total': int,
            'page': int,
            'size': int,
            'pages': int
        }

        self.attribute_map = {
            'data': 'data',
            'total': 'total',
            'page': 'page',
            'size': 'size',
            'pages': 'pages'
        }

        self._data = data
        self._total = total
        self._page = page
        self._size = size
        self._pages = pages

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DataPageItemSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DataPage_ItemSchema_ of this DataPageItemSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this DataPageItemSchema.


        :return: The data of this DataPageItemSchema.
        :rtype: List[ItemSchema]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this DataPageItemSchema.


        :param data: The data of this DataPageItemSchema.
        :type data: List[ItemSchema]
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data

    @property
    def total(self):
        """Gets the total of this DataPageItemSchema.


        :return: The total of this DataPageItemSchema.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this DataPageItemSchema.


        :param total: The total of this DataPageItemSchema.
        :type total: int
        """
        if total is not None and total < 0:
            raise ValueError("Invalid value for `total`, must be a value greater than or equal to `0`")

        self._total = total

    @property
    def page(self):
        """Gets the page of this DataPageItemSchema.


        :return: The page of this DataPageItemSchema.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this DataPageItemSchema.


        :param page: The page of this DataPageItemSchema.
        :type page: int
        """
        if page is not None and page < 1:
            raise ValueError("Invalid value for `page`, must be a value greater than or equal to `1`")

        self._page = page

    @property
    def size(self):
        """Gets the size of this DataPageItemSchema.


        :return: The size of this DataPageItemSchema.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this DataPageItemSchema.


        :param size: The size of this DataPageItemSchema.
        :type size: int
        """
        if size is not None and size < 1:
            raise ValueError("Invalid value for `size`, must be a value greater than or equal to `1`")

        self._size = size

    @property
    def pages(self):
        """Gets the pages of this DataPageItemSchema.


        :return: The pages of this DataPageItemSchema.
        :rtype: int
        """
        return self._pages

    @pages.setter
    def pages(self, pages):
        """Sets the pages of this DataPageItemSchema.


        :param pages: The pages of this DataPageItemSchema.
        :type pages: int
        """
        if pages is not None and pages < 0:
            raise ValueError("Invalid value for `pages`, must be a value greater than or equal to `0`")

        self._pages = pages
