# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
import re
from artifactsmmo import util


class DeleteCharacterSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None):
        """DeleteCharacterSchema - a model defined in OpenAPI

        :param name: The name of this DeleteCharacterSchema.
        """
        self.openapi_types = {
            'name': str
        }

        self.attribute_map = {
            'name': 'name'
        }

        self._name = name

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DeleteCharacterSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DeleteCharacterSchema of this DeleteCharacterSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this DeleteCharacterSchema.

        Character name.

        :return: The name of this DeleteCharacterSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DeleteCharacterSchema.

        Character name.

        :param name: The name of this DeleteCharacterSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")
        if name is not None and len(name) > 12:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `12`")
        if name is not None and len(name) < 3:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `3`")
        if name is not None and not re.search(r'^[a-zA-Z0-9_-]+$', name):
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._name = name
