# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo.models.simple_item_schema import SimpleItemSchema
from artifactsmmo import util


class DeleteItemSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, item: SimpleItemSchema=None, character: CharacterSchema=None):
        """DeleteItemSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this DeleteItemSchema.
        :param item: The item of this DeleteItemSchema.
        :param character: The character of this DeleteItemSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'item': SimpleItemSchema,
            'character': CharacterSchema
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'item': 'item',
            'character': 'character'
        }

        self._cooldown = cooldown
        self._item = item
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DeleteItemSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DeleteItemSchema of this DeleteItemSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this DeleteItemSchema.

        Cooldown details.

        :return: The cooldown of this DeleteItemSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this DeleteItemSchema.

        Cooldown details.

        :param cooldown: The cooldown of this DeleteItemSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def item(self):
        """Gets the item of this DeleteItemSchema.

        Item details.

        :return: The item of this DeleteItemSchema.
        :rtype: SimpleItemSchema
        """
        return self._item

    @item.setter
    def item(self, item):
        """Sets the item of this DeleteItemSchema.

        Item details.

        :param item: The item of this DeleteItemSchema.
        :type item: SimpleItemSchema
        """
        if item is None:
            raise ValueError("Invalid value for `item`, must not be `None`")

        self._item = item

    @property
    def character(self):
        """Gets the character of this DeleteItemSchema.

        Player details.

        :return: The character of this DeleteItemSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this DeleteItemSchema.

        Player details.

        :param character: The character of this DeleteItemSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
