# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.delete_item_schema import DeleteItemSchema
from artifactsmmo import util


class DeleteItemResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: DeleteItemSchema=None):
        """DeleteItemResponseSchema - a model defined in OpenAPI

        :param data: The data of this DeleteItemResponseSchema.
        """
        self.openapi_types = {
            'data': DeleteItemSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DeleteItemResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DeleteItemResponseSchema of this DeleteItemResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this DeleteItemResponseSchema.


        :return: The data of this DeleteItemResponseSchema.
        :rtype: DeleteItemSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this DeleteItemResponseSchema.


        :param data: The data of this DeleteItemResponseSchema.
        :type data: DeleteItemSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
