# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class DepositWithdrawGoldSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, quantity: int=None):
        """DepositWithdrawGoldSchema - a model defined in OpenAPI

        :param quantity: The quantity of this DepositWithdrawGoldSchema.
        """
        self.openapi_types = {
            'quantity': int
        }

        self.attribute_map = {
            'quantity': 'quantity'
        }

        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt: dict) -> 'DepositWithdrawGoldSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The DepositWithdrawGoldSchema of this DepositWithdrawGoldSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def quantity(self):
        """Gets the quantity of this DepositWithdrawGoldSchema.

        Quantity of gold.

        :return: The quantity of this DepositWithdrawGoldSchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this DepositWithdrawGoldSchema.

        Quantity of gold.

        :param quantity: The quantity of this DepositWithdrawGoldSchema.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")
        if quantity is not None and quantity < 1:
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `1`")

        self._quantity = quantity
