# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class EffectType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    EQUIPMENT = 'equipment'
    CONSUMABLE = 'consumable'
    COMBAT = 'combat'

    def __init__(self):
        """EffectType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'EffectType':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The EffectType of this EffectType.
        """
        return util.deserialize_model(dikt, cls)
