# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.effect_schema import EffectSchema
from artifactsmmo import util


class EffectResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: EffectSchema=None):
        """EffectResponseSchema - a model defined in OpenAPI

        :param data: The data of this EffectResponseSchema.
        """
        self.openapi_types = {
            'data': EffectSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'EffectResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The EffectResponseSchema of this EffectResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this EffectResponseSchema.


        :return: The data of this EffectResponseSchema.
        :rtype: EffectSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this EffectResponseSchema.


        :param data: The data of this EffectResponseSchema.
        :type data: EffectSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
