# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.item_slot import ItemSlot
import re
from artifactsmmo import util


class EquipSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, slot: ItemSlot=None, quantity: int=1):
        """EquipSchema - a model defined in OpenAPI

        :param code: The code of this EquipSchema.
        :param slot: The slot of this EquipSchema.
        :param quantity: The quantity of this EquipSchema.
        """
        self.openapi_types = {
            'code': str,
            'slot': ItemSlot,
            'quantity': int
        }

        self.attribute_map = {
            'code': 'code',
            'slot': 'slot',
            'quantity': 'quantity'
        }

        self._code = code
        self._slot = slot
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt: dict) -> 'EquipSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The EquipSchema of this EquipSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this EquipSchema.

        Item code.

        :return: The code of this EquipSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this EquipSchema.

        Item code.

        :param code: The code of this EquipSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")
        if code is not None and not re.search(r'^[a-zA-Z0-9_-]+$', code):
            raise ValueError("Invalid value for `code`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._code = code

    @property
    def slot(self):
        """Gets the slot of this EquipSchema.

        Item slot.

        :return: The slot of this EquipSchema.
        :rtype: ItemSlot
        """
        return self._slot

    @slot.setter
    def slot(self, slot):
        """Sets the slot of this EquipSchema.

        Item slot.

        :param slot: The slot of this EquipSchema.
        :type slot: ItemSlot
        """
        if slot is None:
            raise ValueError("Invalid value for `slot`, must not be `None`")

        self._slot = slot

    @property
    def quantity(self):
        """Gets the quantity of this EquipSchema.

        Item quantity. Applicable to utilities only.

        :return: The quantity of this EquipSchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this EquipSchema.

        Item quantity. Applicable to utilities only.

        :param quantity: The quantity of this EquipSchema.
        :type quantity: int
        """
        if quantity is not None and quantity > 100:
            raise ValueError("Invalid value for `quantity`, must be a value less than or equal to `100`")
        if quantity is not None and quantity < 1:
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `1`")

        self._quantity = quantity
