# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo.models.item_schema import ItemSchema
from artifactsmmo.models.item_slot import ItemSlot
from artifactsmmo import util


class EquipRequestSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, slot: ItemSlot=None, item: ItemSchema=None, character: CharacterSchema=None):
        """EquipRequestSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this EquipRequestSchema.
        :param slot: The slot of this EquipRequestSchema.
        :param item: The item of this EquipRequestSchema.
        :param character: The character of this EquipRequestSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'slot': ItemSlot,
            'item': ItemSchema,
            'character': CharacterSchema
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'slot': 'slot',
            'item': 'item',
            'character': 'character'
        }

        self._cooldown = cooldown
        self._slot = slot
        self._item = item
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'EquipRequestSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The EquipRequestSchema of this EquipRequestSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this EquipRequestSchema.

        Cooldown details.

        :return: The cooldown of this EquipRequestSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this EquipRequestSchema.

        Cooldown details.

        :param cooldown: The cooldown of this EquipRequestSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def slot(self):
        """Gets the slot of this EquipRequestSchema.

        Item slot.

        :return: The slot of this EquipRequestSchema.
        :rtype: ItemSlot
        """
        return self._slot

    @slot.setter
    def slot(self, slot):
        """Sets the slot of this EquipRequestSchema.

        Item slot.

        :param slot: The slot of this EquipRequestSchema.
        :type slot: ItemSlot
        """
        if slot is None:
            raise ValueError("Invalid value for `slot`, must not be `None`")

        self._slot = slot

    @property
    def item(self):
        """Gets the item of this EquipRequestSchema.

        Item details.

        :return: The item of this EquipRequestSchema.
        :rtype: ItemSchema
        """
        return self._item

    @item.setter
    def item(self, item):
        """Sets the item of this EquipRequestSchema.

        Item details.

        :param item: The item of this EquipRequestSchema.
        :type item: ItemSchema
        """
        if item is None:
            raise ValueError("Invalid value for `item`, must not be `None`")

        self._item = item

    @property
    def character(self):
        """Gets the character of this EquipRequestSchema.

        Player details.

        :return: The character of this EquipRequestSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this EquipRequestSchema.

        Player details.

        :param character: The character of this EquipRequestSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
