# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class ErrorSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, message: str=None, data: Dict[str, object]=None):
        """ErrorSchema - a model defined in OpenAPI

        :param code: The code of this ErrorSchema.
        :param message: The message of this ErrorSchema.
        :param data: The data of this ErrorSchema.
        """
        self.openapi_types = {
            'code': int,
            'message': str,
            'data': Dict[str, object]
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'data': 'data'
        }

        self._code = code
        self._message = message
        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ErrorSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ErrorSchema of this ErrorSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this ErrorSchema.

        Error code

        :return: The code of this ErrorSchema.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ErrorSchema.

        Error code

        :param code: The code of this ErrorSchema.
        :type code: int
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def message(self):
        """Gets the message of this ErrorSchema.

        Error message

        :return: The message of this ErrorSchema.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorSchema.

        Error message

        :param message: The message of this ErrorSchema.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")

        self._message = message

    @property
    def data(self):
        """Gets the data of this ErrorSchema.

        Additional error data (used primarily for validation errors)

        :return: The data of this ErrorSchema.
        :rtype: Dict[str, object]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ErrorSchema.

        Additional error data (used primarily for validation errors)

        :param data: The data of this ErrorSchema.
        :type data: Dict[str, object]
        """

        self._data = data
