# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.event_content_schema import EventContentSchema
from artifactsmmo.models.event_map_schema import EventMapSchema
from artifactsmmo import util


class EventSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, code: str=None, content: EventContentSchema=None, maps: List[EventMapSchema]=None, duration: int=None, rate: int=None):
        """EventSchema - a model defined in OpenAPI

        :param name: The name of this EventSchema.
        :param code: The code of this EventSchema.
        :param content: The content of this EventSchema.
        :param maps: The maps of this EventSchema.
        :param duration: The duration of this EventSchema.
        :param rate: The rate of this EventSchema.
        """
        self.openapi_types = {
            'name': str,
            'code': str,
            'content': EventContentSchema,
            'maps': List[EventMapSchema],
            'duration': int,
            'rate': int
        }

        self.attribute_map = {
            'name': 'name',
            'code': 'code',
            'content': 'content',
            'maps': 'maps',
            'duration': 'duration',
            'rate': 'rate'
        }

        self._name = name
        self._code = code
        self._content = content
        self._maps = maps
        self._duration = duration
        self._rate = rate

    @classmethod
    def from_dict(cls, dikt: dict) -> 'EventSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The EventSchema of this EventSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this EventSchema.

        Name of the event.

        :return: The name of this EventSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EventSchema.

        Name of the event.

        :param name: The name of this EventSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def code(self):
        """Gets the code of this EventSchema.

        Code of the event.

        :return: The code of this EventSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this EventSchema.

        Code of the event.

        :param code: The code of this EventSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def content(self):
        """Gets the content of this EventSchema.

        Content of the event.

        :return: The content of this EventSchema.
        :rtype: EventContentSchema
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this EventSchema.

        Content of the event.

        :param content: The content of this EventSchema.
        :type content: EventContentSchema
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")

        self._content = content

    @property
    def maps(self):
        """Gets the maps of this EventSchema.

        Map list of the event.

        :return: The maps of this EventSchema.
        :rtype: List[EventMapSchema]
        """
        return self._maps

    @maps.setter
    def maps(self, maps):
        """Sets the maps of this EventSchema.

        Map list of the event.

        :param maps: The maps of this EventSchema.
        :type maps: List[EventMapSchema]
        """
        if maps is None:
            raise ValueError("Invalid value for `maps`, must not be `None`")

        self._maps = maps

    @property
    def duration(self):
        """Gets the duration of this EventSchema.

        Duration in minutes.

        :return: The duration of this EventSchema.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this EventSchema.

        Duration in minutes.

        :param duration: The duration of this EventSchema.
        :type duration: int
        """
        if duration is None:
            raise ValueError("Invalid value for `duration`, must not be `None`")

        self._duration = duration

    @property
    def rate(self):
        """Gets the rate of this EventSchema.

        Rate spawn of the event. (1/rate every minute)

        :return: The rate of this EventSchema.
        :rtype: int
        """
        return self._rate

    @rate.setter
    def rate(self, rate):
        """Sets the rate of this EventSchema.

        Rate spawn of the event. (1/rate every minute)

        :param rate: The rate of this EventSchema.
        :type rate: int
        """
        if rate is None:
            raise ValueError("Invalid value for `rate`, must not be `None`")

        self._rate = rate
