# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class FightRequestSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, participants: List[str]=[]):
        """FightRequestSchema - a model defined in OpenAPI

        :param participants: The participants of this FightRequestSchema.
        """
        self.openapi_types = {
            'participants': List[str]
        }

        self.attribute_map = {
            'participants': 'participants'
        }

        self._participants = participants

    @classmethod
    def from_dict(cls, dikt: dict) -> 'FightRequestSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The FightRequestSchema of this FightRequestSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def participants(self):
        """Gets the participants of this FightRequestSchema.

        Optional list of additional character names to include in the fight (max 2 additional characters).

        :return: The participants of this FightRequestSchema.
        :rtype: List[str]
        """
        return self._participants

    @participants.setter
    def participants(self, participants):
        """Sets the participants of this FightRequestSchema.

        Optional list of additional character names to include in the fight (max 2 additional characters).

        :param participants: The participants of this FightRequestSchema.
        :type participants: List[str]
        """
        if participants is not None and len(participants) > 2:
            raise ValueError("Invalid value for `participants`, number of items must be less than or equal to `2`")

        self._participants = participants
