# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
import re
from artifactsmmo import util


class GEBuyOrderCreationSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, quantity: int=None, price: int=None):
        """GEBuyOrderCreationSchema - a model defined in OpenAPI

        :param code: The code of this GEBuyOrderCreationSchema.
        :param quantity: The quantity of this GEBuyOrderCreationSchema.
        :param price: The price of this GEBuyOrderCreationSchema.
        """
        self.openapi_types = {
            'code': str,
            'quantity': int,
            'price': int
        }

        self.attribute_map = {
            'code': 'code',
            'quantity': 'quantity',
            'price': 'price'
        }

        self._code = code
        self._quantity = quantity
        self._price = price

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GEBuyOrderCreationSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GEBuyOrderCreationSchema of this GEBuyOrderCreationSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this GEBuyOrderCreationSchema.

        Item code.

        :return: The code of this GEBuyOrderCreationSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this GEBuyOrderCreationSchema.

        Item code.

        :param code: The code of this GEBuyOrderCreationSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")
        if code is not None and not re.search(r'^[a-zA-Z0-9_-]+$', code):
            raise ValueError("Invalid value for `code`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._code = code

    @property
    def quantity(self):
        """Gets the quantity of this GEBuyOrderCreationSchema.

        Item quantity.

        :return: The quantity of this GEBuyOrderCreationSchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this GEBuyOrderCreationSchema.

        Item quantity.

        :param quantity: The quantity of this GEBuyOrderCreationSchema.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")
        if quantity is not None and quantity > 100:
            raise ValueError("Invalid value for `quantity`, must be a value less than or equal to `100`")
        if quantity is not None and quantity < 1:
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `1`")

        self._quantity = quantity

    @property
    def price(self):
        """Gets the price of this GEBuyOrderCreationSchema.

        Item price per unit.

        :return: The price of this GEBuyOrderCreationSchema.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this GEBuyOrderCreationSchema.

        Item price per unit.

        :param price: The price of this GEBuyOrderCreationSchema.
        :type price: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")
        if price is not None and price > 1000000000:
            raise ValueError("Invalid value for `price`, must be a value less than or equal to `1000000000`")
        if price is not None and price < 1:
            raise ValueError("Invalid value for `price`, must be a value greater than or equal to `1`")

        self._price = price
