# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class GECancelOrderSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None):
        """GECancelOrderSchema - a model defined in OpenAPI

        :param id: The id of this GECancelOrderSchema.
        """
        self.openapi_types = {
            'id': str
        }

        self.attribute_map = {
            'id': 'id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GECancelOrderSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GECancelOrderSchema of this GECancelOrderSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this GECancelOrderSchema.

        Order id.

        :return: The id of this GECancelOrderSchema.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GECancelOrderSchema.

        Order id.

        :param id: The id of this GECancelOrderSchema.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id
