# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo.models.ge_order_created_schema import GEOrderCreatedSchema
from artifactsmmo import util


class GEOrderTransactionSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, order: GEOrderCreatedSchema=None, character: CharacterSchema=None):
        """GEOrderTransactionSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this GEOrderTransactionSchema.
        :param order: The order of this GEOrderTransactionSchema.
        :param character: The character of this GEOrderTransactionSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'order': GEOrderCreatedSchema,
            'character': CharacterSchema
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'order': 'order',
            'character': 'character'
        }

        self._cooldown = cooldown
        self._order = order
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GEOrderTransactionSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GEOrderTransactionSchema of this GEOrderTransactionSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this GEOrderTransactionSchema.

        Cooldown details.

        :return: The cooldown of this GEOrderTransactionSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this GEOrderTransactionSchema.

        Cooldown details.

        :param cooldown: The cooldown of this GEOrderTransactionSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def order(self):
        """Gets the order of this GEOrderTransactionSchema.

        Order details.

        :return: The order of this GEOrderTransactionSchema.
        :rtype: GEOrderCreatedSchema
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this GEOrderTransactionSchema.

        Order details.

        :param order: The order of this GEOrderTransactionSchema.
        :type order: GEOrderCreatedSchema
        """
        if order is None:
            raise ValueError("Invalid value for `order`, must not be `None`")

        self._order = order

    @property
    def character(self):
        """Gets the character of this GEOrderTransactionSchema.

        Character details.

        :return: The character of this GEOrderTransactionSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this GEOrderTransactionSchema.

        Character details.

        :param character: The character of this GEOrderTransactionSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
