# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
import re
from artifactsmmo import util


class GEOrderCreatedSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, created_at: datetime=None, code: str=None, quantity: int=None, price: int=None, total_price: int=None):
        """GEOrderCreatedSchema - a model defined in OpenAPI

        :param id: The id of this GEOrderCreatedSchema.
        :param created_at: The created_at of this GEOrderCreatedSchema.
        :param code: The code of this GEOrderCreatedSchema.
        :param quantity: The quantity of this GEOrderCreatedSchema.
        :param price: The price of this GEOrderCreatedSchema.
        :param total_price: The total_price of this GEOrderCreatedSchema.
        """
        self.openapi_types = {
            'id': str,
            'created_at': datetime,
            'code': str,
            'quantity': int,
            'price': int,
            'total_price': int
        }

        self.attribute_map = {
            'id': 'id',
            'created_at': 'created_at',
            'code': 'code',
            'quantity': 'quantity',
            'price': 'price',
            'total_price': 'total_price'
        }

        self._id = id
        self._created_at = created_at
        self._code = code
        self._quantity = quantity
        self._price = price
        self._total_price = total_price

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GEOrderCreatedSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GEOrderCreatedSchema of this GEOrderCreatedSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this GEOrderCreatedSchema.

        Order id.

        :return: The id of this GEOrderCreatedSchema.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GEOrderCreatedSchema.

        Order id.

        :param id: The id of this GEOrderCreatedSchema.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this GEOrderCreatedSchema.

        Order created at.

        :return: The created_at of this GEOrderCreatedSchema.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this GEOrderCreatedSchema.

        Order created at.

        :param created_at: The created_at of this GEOrderCreatedSchema.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")

        self._created_at = created_at

    @property
    def code(self):
        """Gets the code of this GEOrderCreatedSchema.

        Item code.

        :return: The code of this GEOrderCreatedSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this GEOrderCreatedSchema.

        Item code.

        :param code: The code of this GEOrderCreatedSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")
        if code is not None and not re.search(r'^[a-zA-Z0-9_-]+$', code):
            raise ValueError("Invalid value for `code`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._code = code

    @property
    def quantity(self):
        """Gets the quantity of this GEOrderCreatedSchema.

        Item quantity.

        :return: The quantity of this GEOrderCreatedSchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this GEOrderCreatedSchema.

        Item quantity.

        :param quantity: The quantity of this GEOrderCreatedSchema.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")
        if quantity is not None and quantity > 100:
            raise ValueError("Invalid value for `quantity`, must be a value less than or equal to `100`")
        if quantity is not None and quantity < 1:
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `1`")

        self._quantity = quantity

    @property
    def price(self):
        """Gets the price of this GEOrderCreatedSchema.

        Item price per unit.

        :return: The price of this GEOrderCreatedSchema.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this GEOrderCreatedSchema.

        Item price per unit.

        :param price: The price of this GEOrderCreatedSchema.
        :type price: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")
        if price is not None and price < 1:
            raise ValueError("Invalid value for `price`, must be a value greater than or equal to `1`")

        self._price = price

    @property
    def total_price(self):
        """Gets the total_price of this GEOrderCreatedSchema.

        Total price.

        :return: The total_price of this GEOrderCreatedSchema.
        :rtype: int
        """
        return self._total_price

    @total_price.setter
    def total_price(self, total_price):
        """Sets the total_price of this GEOrderCreatedSchema.

        Total price.

        :param total_price: The total_price of this GEOrderCreatedSchema.
        :type total_price: int
        """
        if total_price is None:
            raise ValueError("Invalid value for `total_price`, must not be `None`")
        if total_price is not None and total_price < 1:
            raise ValueError("Invalid value for `total_price`, must be a value greater than or equal to `1`")

        self._total_price = total_price
