# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class GeOrderHistorySchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, order_id: str=None, seller: str=None, buyer: str=None, code: str=None, quantity: int=None, price: int=None, sold_at: datetime=None):
        """GeOrderHistorySchema - a model defined in OpenAPI

        :param order_id: The order_id of this GeOrderHistorySchema.
        :param seller: The seller of this GeOrderHistorySchema.
        :param buyer: The buyer of this GeOrderHistorySchema.
        :param code: The code of this GeOrderHistorySchema.
        :param quantity: The quantity of this GeOrderHistorySchema.
        :param price: The price of this GeOrderHistorySchema.
        :param sold_at: The sold_at of this GeOrderHistorySchema.
        """
        self.openapi_types = {
            'order_id': str,
            'seller': str,
            'buyer': str,
            'code': str,
            'quantity': int,
            'price': int,
            'sold_at': datetime
        }

        self.attribute_map = {
            'order_id': 'order_id',
            'seller': 'seller',
            'buyer': 'buyer',
            'code': 'code',
            'quantity': 'quantity',
            'price': 'price',
            'sold_at': 'sold_at'
        }

        self._order_id = order_id
        self._seller = seller
        self._buyer = buyer
        self._code = code
        self._quantity = quantity
        self._price = price
        self._sold_at = sold_at

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GeOrderHistorySchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GeOrderHistorySchema of this GeOrderHistorySchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self):
        """Gets the order_id of this GeOrderHistorySchema.

        Order id.

        :return: The order_id of this GeOrderHistorySchema.
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this GeOrderHistorySchema.

        Order id.

        :param order_id: The order_id of this GeOrderHistorySchema.
        :type order_id: str
        """
        if order_id is None:
            raise ValueError("Invalid value for `order_id`, must not be `None`")

        self._order_id = order_id

    @property
    def seller(self):
        """Gets the seller of this GeOrderHistorySchema.

        Seller account name.

        :return: The seller of this GeOrderHistorySchema.
        :rtype: str
        """
        return self._seller

    @seller.setter
    def seller(self, seller):
        """Sets the seller of this GeOrderHistorySchema.

        Seller account name.

        :param seller: The seller of this GeOrderHistorySchema.
        :type seller: str
        """
        if seller is None:
            raise ValueError("Invalid value for `seller`, must not be `None`")

        self._seller = seller

    @property
    def buyer(self):
        """Gets the buyer of this GeOrderHistorySchema.

        Buyer account name.

        :return: The buyer of this GeOrderHistorySchema.
        :rtype: str
        """
        return self._buyer

    @buyer.setter
    def buyer(self, buyer):
        """Sets the buyer of this GeOrderHistorySchema.

        Buyer account name.

        :param buyer: The buyer of this GeOrderHistorySchema.
        :type buyer: str
        """
        if buyer is None:
            raise ValueError("Invalid value for `buyer`, must not be `None`")

        self._buyer = buyer

    @property
    def code(self):
        """Gets the code of this GeOrderHistorySchema.

        Item code.

        :return: The code of this GeOrderHistorySchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this GeOrderHistorySchema.

        Item code.

        :param code: The code of this GeOrderHistorySchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def quantity(self):
        """Gets the quantity of this GeOrderHistorySchema.

        Item quantity.

        :return: The quantity of this GeOrderHistorySchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this GeOrderHistorySchema.

        Item quantity.

        :param quantity: The quantity of this GeOrderHistorySchema.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")
        if quantity is not None and quantity > 100:
            raise ValueError("Invalid value for `quantity`, must be a value less than or equal to `100`")
        if quantity is not None and quantity < 1:
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `1`")

        self._quantity = quantity

    @property
    def price(self):
        """Gets the price of this GeOrderHistorySchema.

        Item price per unit.

        :return: The price of this GeOrderHistorySchema.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this GeOrderHistorySchema.

        Item price per unit.

        :param price: The price of this GeOrderHistorySchema.
        :type price: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")
        if price is not None and price < 1:
            raise ValueError("Invalid value for `price`, must be a value greater than or equal to `1`")

        self._price = price

    @property
    def sold_at(self):
        """Gets the sold_at of this GeOrderHistorySchema.

        Sale datetime.

        :return: The sold_at of this GeOrderHistorySchema.
        :rtype: datetime
        """
        return self._sold_at

    @sold_at.setter
    def sold_at(self, sold_at):
        """Sets the sold_at of this GeOrderHistorySchema.

        Sale datetime.

        :param sold_at: The sold_at of this GeOrderHistorySchema.
        :type sold_at: datetime
        """
        if sold_at is None:
            raise ValueError("Invalid value for `sold_at`, must not be `None`")

        self._sold_at = sold_at
