# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.ge_transaction_list_schema import GETransactionListSchema
from artifactsmmo import util


class GETransactionResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: GETransactionListSchema=None):
        """GETransactionResponseSchema - a model defined in OpenAPI

        :param data: The data of this GETransactionResponseSchema.
        """
        self.openapi_types = {
            'data': GETransactionListSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GETransactionResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GETransactionResponseSchema of this GETransactionResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GETransactionResponseSchema.


        :return: The data of this GETransactionResponseSchema.
        :rtype: GETransactionListSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GETransactionResponseSchema.


        :param data: The data of this GETransactionResponseSchema.
        :type data: GETransactionListSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
