# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo.models.simple_item_schema import SimpleItemSchema
from artifactsmmo import util


class GiveItemDataSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, items: List[SimpleItemSchema]=None, receiver_character: CharacterSchema=None, character: CharacterSchema=None):
        """GiveItemDataSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this GiveItemDataSchema.
        :param items: The items of this GiveItemDataSchema.
        :param receiver_character: The receiver_character of this GiveItemDataSchema.
        :param character: The character of this GiveItemDataSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'items': List[SimpleItemSchema],
            'receiver_character': CharacterSchema,
            'character': CharacterSchema
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'items': 'items',
            'receiver_character': 'receiver_character',
            'character': 'character'
        }

        self._cooldown = cooldown
        self._items = items
        self._receiver_character = receiver_character
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GiveItemDataSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GiveItemDataSchema of this GiveItemDataSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this GiveItemDataSchema.

        Cooldown details.

        :return: The cooldown of this GiveItemDataSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this GiveItemDataSchema.

        Cooldown details.

        :param cooldown: The cooldown of this GiveItemDataSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def items(self):
        """Gets the items of this GiveItemDataSchema.

        Items given.

        :return: The items of this GiveItemDataSchema.
        :rtype: List[SimpleItemSchema]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this GiveItemDataSchema.

        Items given.

        :param items: The items of this GiveItemDataSchema.
        :type items: List[SimpleItemSchema]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")

        self._items = items

    @property
    def receiver_character(self):
        """Gets the receiver_character of this GiveItemDataSchema.

        Character details of the receiving character.

        :return: The receiver_character of this GiveItemDataSchema.
        :rtype: CharacterSchema
        """
        return self._receiver_character

    @receiver_character.setter
    def receiver_character(self, receiver_character):
        """Sets the receiver_character of this GiveItemDataSchema.

        Character details of the receiving character.

        :param receiver_character: The receiver_character of this GiveItemDataSchema.
        :type receiver_character: CharacterSchema
        """
        if receiver_character is None:
            raise ValueError("Invalid value for `receiver_character`, must not be `None`")

        self._receiver_character = receiver_character

    @property
    def character(self):
        """Gets the character of this GiveItemDataSchema.

        Character details of the sending character.

        :return: The character of this GiveItemDataSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this GiveItemDataSchema.

        Character details of the sending character.

        :param character: The character of this GiveItemDataSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
