# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
import re
from artifactsmmo import util


class GiveGoldSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, quantity: int=None, character: str=None):
        """GiveGoldSchema - a model defined in OpenAPI

        :param quantity: The quantity of this GiveGoldSchema.
        :param character: The character of this GiveGoldSchema.
        """
        self.openapi_types = {
            'quantity': int,
            'character': str
        }

        self.attribute_map = {
            'quantity': 'quantity',
            'character': 'character'
        }

        self._quantity = quantity
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GiveGoldSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GiveGoldSchema of this GiveGoldSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def quantity(self):
        """Gets the quantity of this GiveGoldSchema.

        Gold quantity.

        :return: The quantity of this GiveGoldSchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this GiveGoldSchema.

        Gold quantity.

        :param quantity: The quantity of this GiveGoldSchema.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")
        if quantity is not None and quantity < 1:
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `1`")

        self._quantity = quantity

    @property
    def character(self):
        """Gets the character of this GiveGoldSchema.

        Character name. The name of the character who will receive the gold.

        :return: The character of this GiveGoldSchema.
        :rtype: str
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this GiveGoldSchema.

        Character name. The name of the character who will receive the gold.

        :param character: The character of this GiveGoldSchema.
        :type character: str
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")
        if character is not None and not re.search(r'^[a-zA-Z0-9_-]+$', character):
            raise ValueError("Invalid value for `character`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._character = character
