# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.give_item_data_schema import GiveItemDataSchema
from artifactsmmo import util


class GiveItemResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: GiveItemDataSchema=None):
        """GiveItemResponseSchema - a model defined in OpenAPI

        :param data: The data of this GiveItemResponseSchema.
        """
        self.openapi_types = {
            'data': GiveItemDataSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GiveItemResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GiveItemResponseSchema of this GiveItemResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GiveItemResponseSchema.


        :return: The data of this GiveItemResponseSchema.
        :rtype: GiveItemDataSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GiveItemResponseSchema.


        :param data: The data of this GiveItemResponseSchema.
        :type data: GiveItemDataSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
