# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.give_gold_data_schema import GiveGoldDataSchema
from artifactsmmo import util


class GiveGoldResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: GiveGoldDataSchema=None):
        """GiveGoldResponseSchema - a model defined in OpenAPI

        :param data: The data of this GiveGoldResponseSchema.
        """
        self.openapi_types = {
            'data': GiveGoldDataSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GiveGoldResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GiveGoldResponseSchema of this GiveGoldResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this GiveGoldResponseSchema.


        :return: The data of this GiveGoldResponseSchema.
        :rtype: GiveGoldDataSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this GiveGoldResponseSchema.


        :param data: The data of this GiveGoldResponseSchema.
        :type data: GiveGoldDataSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
