# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.simple_item_schema import SimpleItemSchema
import re
from artifactsmmo import util


class GiveItemsSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items: List[SimpleItemSchema]=None, character: str=None):
        """GiveItemsSchema - a model defined in OpenAPI

        :param items: The items of this GiveItemsSchema.
        :param character: The character of this GiveItemsSchema.
        """
        self.openapi_types = {
            'items': List[SimpleItemSchema],
            'character': str
        }

        self.attribute_map = {
            'items': 'items',
            'character': 'character'
        }

        self._items = items
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'GiveItemsSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The GiveItemsSchema of this GiveItemsSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this GiveItemsSchema.

        List of items to give

        :return: The items of this GiveItemsSchema.
        :rtype: List[SimpleItemSchema]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this GiveItemsSchema.

        List of items to give

        :param items: The items of this GiveItemsSchema.
        :type items: List[SimpleItemSchema]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")
        if items is not None and len(items) > 20:
            raise ValueError("Invalid value for `items`, number of items must be less than or equal to `20`")
        if items is not None and len(items) < 1:
            raise ValueError("Invalid value for `items`, number of items must be greater than or equal to `1`")

        self._items = items

    @property
    def character(self):
        """Gets the character of this GiveItemsSchema.

        Character name. The name of the character who will receive the items.

        :return: The character of this GiveItemsSchema.
        :rtype: str
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this GiveItemsSchema.

        Character name. The name of the character who will receive the items.

        :param character: The character of this GiveItemsSchema.
        :type character: str
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")
        if character is not None and not re.search(r'^[a-zA-Z0-9_-]+$', character):
            raise ValueError("Invalid value for `character`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._character = character
