# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.map_content_schema import MapContentSchema
from artifactsmmo.models.transition_schema import TransitionSchema
from artifactsmmo import util


class InteractionSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, content: MapContentSchema=None, transition: TransitionSchema=None):
        """InteractionSchema - a model defined in OpenAPI

        :param content: The content of this InteractionSchema.
        :param transition: The transition of this InteractionSchema.
        """
        self.openapi_types = {
            'content': MapContentSchema,
            'transition': TransitionSchema
        }

        self.attribute_map = {
            'content': 'content',
            'transition': 'transition'
        }

        self._content = content
        self._transition = transition

    @classmethod
    def from_dict(cls, dikt: dict) -> 'InteractionSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The InteractionSchema of this InteractionSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def content(self):
        """Gets the content of this InteractionSchema.

        Content of the map.

        :return: The content of this InteractionSchema.
        :rtype: MapContentSchema
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this InteractionSchema.

        Content of the map.

        :param content: The content of this InteractionSchema.
        :type content: MapContentSchema
        """

        self._content = content

    @property
    def transition(self):
        """Gets the transition of this InteractionSchema.

        Transition to another map.

        :return: The transition of this InteractionSchema.
        :rtype: TransitionSchema
        """
        return self._transition

    @transition.setter
    def transition(self, transition):
        """Sets the transition of this InteractionSchema.

        Transition to another map.

        :param transition: The transition of this InteractionSchema.
        :type transition: TransitionSchema
        """

        self._transition = transition
