# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.condition_schema import ConditionSchema
from artifactsmmo.models.craft_schema import CraftSchema
from artifactsmmo.models.simple_effect_schema import SimpleEffectSchema
from artifactsmmo import util


class ItemSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, code: str=None, level: int=None, type: str=None, subtype: str=None, description: str=None, conditions: List[ConditionSchema]=None, effects: List[SimpleEffectSchema]=None, craft: CraftSchema=None, tradeable: bool=None):
        """ItemSchema - a model defined in OpenAPI

        :param name: The name of this ItemSchema.
        :param code: The code of this ItemSchema.
        :param level: The level of this ItemSchema.
        :param type: The type of this ItemSchema.
        :param subtype: The subtype of this ItemSchema.
        :param description: The description of this ItemSchema.
        :param conditions: The conditions of this ItemSchema.
        :param effects: The effects of this ItemSchema.
        :param craft: The craft of this ItemSchema.
        :param tradeable: The tradeable of this ItemSchema.
        """
        self.openapi_types = {
            'name': str,
            'code': str,
            'level': int,
            'type': str,
            'subtype': str,
            'description': str,
            'conditions': List[ConditionSchema],
            'effects': List[SimpleEffectSchema],
            'craft': CraftSchema,
            'tradeable': bool
        }

        self.attribute_map = {
            'name': 'name',
            'code': 'code',
            'level': 'level',
            'type': 'type',
            'subtype': 'subtype',
            'description': 'description',
            'conditions': 'conditions',
            'effects': 'effects',
            'craft': 'craft',
            'tradeable': 'tradeable'
        }

        self._name = name
        self._code = code
        self._level = level
        self._type = type
        self._subtype = subtype
        self._description = description
        self._conditions = conditions
        self._effects = effects
        self._craft = craft
        self._tradeable = tradeable

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ItemSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ItemSchema of this ItemSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this ItemSchema.

        Item name.

        :return: The name of this ItemSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ItemSchema.

        Item name.

        :param name: The name of this ItemSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def code(self):
        """Gets the code of this ItemSchema.

        Item code. This is the item's unique identifier (ID).

        :return: The code of this ItemSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ItemSchema.

        Item code. This is the item's unique identifier (ID).

        :param code: The code of this ItemSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def level(self):
        """Gets the level of this ItemSchema.

        Item level.

        :return: The level of this ItemSchema.
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this ItemSchema.

        Item level.

        :param level: The level of this ItemSchema.
        :type level: int
        """
        if level is None:
            raise ValueError("Invalid value for `level`, must not be `None`")
        if level is not None and level < 1:
            raise ValueError("Invalid value for `level`, must be a value greater than or equal to `1`")

        self._level = level

    @property
    def type(self):
        """Gets the type of this ItemSchema.

        Item type.

        :return: The type of this ItemSchema.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ItemSchema.

        Item type.

        :param type: The type of this ItemSchema.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def subtype(self):
        """Gets the subtype of this ItemSchema.

        Item subtype.

        :return: The subtype of this ItemSchema.
        :rtype: str
        """
        return self._subtype

    @subtype.setter
    def subtype(self, subtype):
        """Sets the subtype of this ItemSchema.

        Item subtype.

        :param subtype: The subtype of this ItemSchema.
        :type subtype: str
        """
        if subtype is None:
            raise ValueError("Invalid value for `subtype`, must not be `None`")

        self._subtype = subtype

    @property
    def description(self):
        """Gets the description of this ItemSchema.

        Item description.

        :return: The description of this ItemSchema.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ItemSchema.

        Item description.

        :param description: The description of this ItemSchema.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")

        self._description = description

    @property
    def conditions(self):
        """Gets the conditions of this ItemSchema.

        Item conditions. If applicable. Conditions for using or equipping the item.

        :return: The conditions of this ItemSchema.
        :rtype: List[ConditionSchema]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this ItemSchema.

        Item conditions. If applicable. Conditions for using or equipping the item.

        :param conditions: The conditions of this ItemSchema.
        :type conditions: List[ConditionSchema]
        """

        self._conditions = conditions

    @property
    def effects(self):
        """Gets the effects of this ItemSchema.

        List of object effects. For equipment, it will include item stats.

        :return: The effects of this ItemSchema.
        :rtype: List[SimpleEffectSchema]
        """
        return self._effects

    @effects.setter
    def effects(self, effects):
        """Sets the effects of this ItemSchema.

        List of object effects. For equipment, it will include item stats.

        :param effects: The effects of this ItemSchema.
        :type effects: List[SimpleEffectSchema]
        """

        self._effects = effects

    @property
    def craft(self):
        """Gets the craft of this ItemSchema.

        Craft information. If applicable.

        :return: The craft of this ItemSchema.
        :rtype: CraftSchema
        """
        return self._craft

    @craft.setter
    def craft(self, craft):
        """Sets the craft of this ItemSchema.

        Craft information. If applicable.

        :param craft: The craft of this ItemSchema.
        :type craft: CraftSchema
        """

        self._craft = craft

    @property
    def tradeable(self):
        """Gets the tradeable of this ItemSchema.

        Item tradeable status. A non-tradeable item cannot be exchanged or sold.

        :return: The tradeable of this ItemSchema.
        :rtype: bool
        """
        return self._tradeable

    @tradeable.setter
    def tradeable(self, tradeable):
        """Sets the tradeable of this ItemSchema.

        Item tradeable status. A non-tradeable item cannot be exchanged or sold.

        :param tradeable: The tradeable of this ItemSchema.
        :type tradeable: bool
        """
        if tradeable is None:
            raise ValueError("Invalid value for `tradeable`, must not be `None`")

        self._tradeable = tradeable
