# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class ItemSlot(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    WEAPON = 'weapon'
    SHIELD = 'shield'
    HELMET = 'helmet'
    BODY_ARMOR = 'body_armor'
    LEG_ARMOR = 'leg_armor'
    BOOTS = 'boots'
    RING1 = 'ring1'
    RING2 = 'ring2'
    AMULET = 'amulet'
    ARTIFACT1 = 'artifact1'
    ARTIFACT2 = 'artifact2'
    ARTIFACT3 = 'artifact3'
    UTILITY1 = 'utility1'
    UTILITY2 = 'utility2'
    BAG = 'bag'
    RUNE = 'rune'

    def __init__(self):
        """ItemSlot - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ItemSlot':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ItemSlot of this ItemSlot.
        """
        return util.deserialize_model(dikt, cls)
