# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.log_type import LogType
from artifactsmmo import util


class LogSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, character: str=None, account: str=None, type: LogType=None, description: str=None, content: object=None, cooldown: int=None, cooldown_expiration: datetime=None, created_at: datetime=None):
        """LogSchema - a model defined in OpenAPI

        :param character: The character of this LogSchema.
        :param account: The account of this LogSchema.
        :param type: The type of this LogSchema.
        :param description: The description of this LogSchema.
        :param content: The content of this LogSchema.
        :param cooldown: The cooldown of this LogSchema.
        :param cooldown_expiration: The cooldown_expiration of this LogSchema.
        :param created_at: The created_at of this LogSchema.
        """
        self.openapi_types = {
            'character': str,
            'account': str,
            'type': LogType,
            'description': str,
            'content': object,
            'cooldown': int,
            'cooldown_expiration': datetime,
            'created_at': datetime
        }

        self.attribute_map = {
            'character': 'character',
            'account': 'account',
            'type': 'type',
            'description': 'description',
            'content': 'content',
            'cooldown': 'cooldown',
            'cooldown_expiration': 'cooldown_expiration',
            'created_at': 'created_at'
        }

        self._character = character
        self._account = account
        self._type = type
        self._description = description
        self._content = content
        self._cooldown = cooldown
        self._cooldown_expiration = cooldown_expiration
        self._created_at = created_at

    @classmethod
    def from_dict(cls, dikt: dict) -> 'LogSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The LogSchema of this LogSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def character(self):
        """Gets the character of this LogSchema.

        Character name.

        :return: The character of this LogSchema.
        :rtype: str
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this LogSchema.

        Character name.

        :param character: The character of this LogSchema.
        :type character: str
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character

    @property
    def account(self):
        """Gets the account of this LogSchema.

        Account character.

        :return: The account of this LogSchema.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this LogSchema.

        Account character.

        :param account: The account of this LogSchema.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")

        self._account = account

    @property
    def type(self):
        """Gets the type of this LogSchema.

        Type of action.

        :return: The type of this LogSchema.
        :rtype: LogType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LogSchema.

        Type of action.

        :param type: The type of this LogSchema.
        :type type: LogType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def description(self):
        """Gets the description of this LogSchema.

        Description of action.

        :return: The description of this LogSchema.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this LogSchema.

        Description of action.

        :param description: The description of this LogSchema.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")

        self._description = description

    @property
    def content(self):
        """Gets the content of this LogSchema.


        :return: The content of this LogSchema.
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this LogSchema.


        :param content: The content of this LogSchema.
        :type content: object
        """
#        if content is None:
#            raise ValueError("Invalid value for `content`, must not be `None`")

        self._content = content

    @property
    def cooldown(self):
        """Gets the cooldown of this LogSchema.

        Cooldown in seconds.

        :return: The cooldown of this LogSchema.
        :rtype: int
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this LogSchema.

        Cooldown in seconds.

        :param cooldown: The cooldown of this LogSchema.
        :type cooldown: int
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def cooldown_expiration(self):
        """Gets the cooldown_expiration of this LogSchema.

        Datetime of cooldown expiration.

        :return: The cooldown_expiration of this LogSchema.
        :rtype: datetime
        """
        return self._cooldown_expiration

    @cooldown_expiration.setter
    def cooldown_expiration(self, cooldown_expiration):
        """Sets the cooldown_expiration of this LogSchema.

        Datetime of cooldown expiration.

        :param cooldown_expiration: The cooldown_expiration of this LogSchema.
        :type cooldown_expiration: datetime
        """
        # if cooldown_expiration is None:
        #     raise ValueError("Invalid value for `cooldown_expiration`, must not be `None`")

        self._cooldown_expiration = cooldown_expiration

    @property
    def created_at(self):
        """Gets the created_at of this LogSchema.

        Datetime of creation.

        :return: The created_at of this LogSchema.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this LogSchema.

        Datetime of creation.

        :param created_at: The created_at of this LogSchema.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")

        self._created_at = created_at
