# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class MapAccessType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    STANDARD = 'standard'
    TELEPORTATION = 'teleportation'
    CONDITIONAL = 'conditional'
    BLOCKED = 'blocked'

    def __init__(self):
        """MapAccessType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MapAccessType':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The MapAccessType of this MapAccessType.
        """
        return util.deserialize_model(dikt, cls)
