# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.access_schema import AccessSchema
from artifactsmmo.models.interaction_schema import InteractionSchema
from artifactsmmo.models.map_layer import MapLayer
from artifactsmmo import util


class MapSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, map_id: int=None, name: str=None, skin: str=None, x: int=None, y: int=None, layer: MapLayer=None, access: AccessSchema=None, interactions: InteractionSchema=None):
        """MapSchema - a model defined in OpenAPI

        :param map_id: The map_id of this MapSchema.
        :param name: The name of this MapSchema.
        :param skin: The skin of this MapSchema.
        :param x: The x of this MapSchema.
        :param y: The y of this MapSchema.
        :param layer: The layer of this MapSchema.
        :param access: The access of this MapSchema.
        :param interactions: The interactions of this MapSchema.
        """
        self.openapi_types = {
            'map_id': int,
            'name': str,
            'skin': str,
            'x': int,
            'y': int,
            'layer': MapLayer,
            'access': AccessSchema,
            'interactions': InteractionSchema
        }

        self.attribute_map = {
            'map_id': 'map_id',
            'name': 'name',
            'skin': 'skin',
            'x': 'x',
            'y': 'y',
            'layer': 'layer',
            'access': 'access',
            'interactions': 'interactions'
        }

        self._map_id = map_id
        self._name = name
        self._skin = skin
        self._x = x
        self._y = y
        self._layer = layer
        self._access = access
        self._interactions = interactions

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MapSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The MapSchema of this MapSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def map_id(self):
        """Gets the map_id of this MapSchema.

        ID of the map.

        :return: The map_id of this MapSchema.
        :rtype: int
        """
        return self._map_id

    @map_id.setter
    def map_id(self, map_id):
        """Sets the map_id of this MapSchema.

        ID of the map.

        :param map_id: The map_id of this MapSchema.
        :type map_id: int
        """
        if map_id is None:
            raise ValueError("Invalid value for `map_id`, must not be `None`")

        self._map_id = map_id

    @property
    def name(self):
        """Gets the name of this MapSchema.

        Name of the map.

        :return: The name of this MapSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MapSchema.

        Name of the map.

        :param name: The name of this MapSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def skin(self):
        """Gets the skin of this MapSchema.

        Skin of the map.

        :return: The skin of this MapSchema.
        :rtype: str
        """
        return self._skin

    @skin.setter
    def skin(self, skin):
        """Sets the skin of this MapSchema.

        Skin of the map.

        :param skin: The skin of this MapSchema.
        :type skin: str
        """
        if skin is None:
            raise ValueError("Invalid value for `skin`, must not be `None`")

        self._skin = skin

    @property
    def x(self):
        """Gets the x of this MapSchema.

        Position X of the map.

        :return: The x of this MapSchema.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this MapSchema.

        Position X of the map.

        :param x: The x of this MapSchema.
        :type x: int
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")

        self._x = x

    @property
    def y(self):
        """Gets the y of this MapSchema.

        Position Y of the map.

        :return: The y of this MapSchema.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this MapSchema.

        Position Y of the map.

        :param y: The y of this MapSchema.
        :type y: int
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")

        self._y = y

    @property
    def layer(self):
        """Gets the layer of this MapSchema.

        Layer of the map.

        :return: The layer of this MapSchema.
        :rtype: MapLayer
        """
        return self._layer

    @layer.setter
    def layer(self, layer):
        """Sets the layer of this MapSchema.

        Layer of the map.

        :param layer: The layer of this MapSchema.
        :type layer: MapLayer
        """
        if layer is None:
            raise ValueError("Invalid value for `layer`, must not be `None`")

        self._layer = layer

    @property
    def access(self):
        """Gets the access of this MapSchema.

        Access information for the map

        :return: The access of this MapSchema.
        :rtype: AccessSchema
        """
        return self._access

    @access.setter
    def access(self, access):
        """Sets the access of this MapSchema.

        Access information for the map

        :param access: The access of this MapSchema.
        :type access: AccessSchema
        """
        if access is None:
            raise ValueError("Invalid value for `access`, must not be `None`")

        self._access = access

    @property
    def interactions(self):
        """Gets the interactions of this MapSchema.

        Interactions available on this map.

        :return: The interactions of this MapSchema.
        :rtype: InteractionSchema
        """
        return self._interactions

    @interactions.setter
    def interactions(self, interactions):
        """Sets the interactions of this MapSchema.

        Interactions available on this map.

        :param interactions: The interactions of this MapSchema.
        :type interactions: InteractionSchema
        """
        if interactions is None:
            raise ValueError("Invalid value for `interactions`, must not be `None`")

        self._interactions = interactions
