# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.drop_rate_schema import DropRateSchema
from artifactsmmo.models.monster_type import MonsterType
from artifactsmmo.models.simple_effect_schema import SimpleEffectSchema
from artifactsmmo import util


class MonsterSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, code: str=None, level: int=None, type: MonsterType=None, hp: int=None, attack_fire: int=None, attack_earth: int=None, attack_water: int=None, attack_air: int=None, res_fire: int=None, res_earth: int=None, res_water: int=None, res_air: int=None, critical_strike: int=None, initiative: int=None, effects: List[SimpleEffectSchema]=None, min_gold: int=None, max_gold: int=None, drops: List[DropRateSchema]=None):
        """MonsterSchema - a model defined in OpenAPI

        :param name: The name of this MonsterSchema.
        :param code: The code of this MonsterSchema.
        :param level: The level of this MonsterSchema.
        :param type: The type of this MonsterSchema.
        :param hp: The hp of this MonsterSchema.
        :param attack_fire: The attack_fire of this MonsterSchema.
        :param attack_earth: The attack_earth of this MonsterSchema.
        :param attack_water: The attack_water of this MonsterSchema.
        :param attack_air: The attack_air of this MonsterSchema.
        :param res_fire: The res_fire of this MonsterSchema.
        :param res_earth: The res_earth of this MonsterSchema.
        :param res_water: The res_water of this MonsterSchema.
        :param res_air: The res_air of this MonsterSchema.
        :param critical_strike: The critical_strike of this MonsterSchema.
        :param initiative: The initiative of this MonsterSchema.
        :param effects: The effects of this MonsterSchema.
        :param min_gold: The min_gold of this MonsterSchema.
        :param max_gold: The max_gold of this MonsterSchema.
        :param drops: The drops of this MonsterSchema.
        """
        self.openapi_types = {
            'name': str,
            'code': str,
            'level': int,
            'type': MonsterType,
            'hp': int,
            'attack_fire': int,
            'attack_earth': int,
            'attack_water': int,
            'attack_air': int,
            'res_fire': int,
            'res_earth': int,
            'res_water': int,
            'res_air': int,
            'critical_strike': int,
            'initiative': int,
            'effects': List[SimpleEffectSchema],
            'min_gold': int,
            'max_gold': int,
            'drops': List[DropRateSchema]
        }

        self.attribute_map = {
            'name': 'name',
            'code': 'code',
            'level': 'level',
            'type': 'type',
            'hp': 'hp',
            'attack_fire': 'attack_fire',
            'attack_earth': 'attack_earth',
            'attack_water': 'attack_water',
            'attack_air': 'attack_air',
            'res_fire': 'res_fire',
            'res_earth': 'res_earth',
            'res_water': 'res_water',
            'res_air': 'res_air',
            'critical_strike': 'critical_strike',
            'initiative': 'initiative',
            'effects': 'effects',
            'min_gold': 'min_gold',
            'max_gold': 'max_gold',
            'drops': 'drops'
        }

        self._name = name
        self._code = code
        self._level = level
        self._type = type
        self._hp = hp
        self._attack_fire = attack_fire
        self._attack_earth = attack_earth
        self._attack_water = attack_water
        self._attack_air = attack_air
        self._res_fire = res_fire
        self._res_earth = res_earth
        self._res_water = res_water
        self._res_air = res_air
        self._critical_strike = critical_strike
        self._initiative = initiative
        self._effects = effects
        self._min_gold = min_gold
        self._max_gold = max_gold
        self._drops = drops

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MonsterSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The MonsterSchema of this MonsterSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this MonsterSchema.

        Name of the monster.

        :return: The name of this MonsterSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MonsterSchema.

        Name of the monster.

        :param name: The name of this MonsterSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def code(self):
        """Gets the code of this MonsterSchema.

        The code of the monster. This is the monster's unique identifier (ID).

        :return: The code of this MonsterSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this MonsterSchema.

        The code of the monster. This is the monster's unique identifier (ID).

        :param code: The code of this MonsterSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def level(self):
        """Gets the level of this MonsterSchema.

        Monster level.

        :return: The level of this MonsterSchema.
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this MonsterSchema.

        Monster level.

        :param level: The level of this MonsterSchema.
        :type level: int
        """
        if level is None:
            raise ValueError("Invalid value for `level`, must not be `None`")

        self._level = level

    @property
    def type(self):
        """Gets the type of this MonsterSchema.

        Monster type.

        :return: The type of this MonsterSchema.
        :rtype: MonsterType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this MonsterSchema.

        Monster type.

        :param type: The type of this MonsterSchema.
        :type type: MonsterType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def hp(self):
        """Gets the hp of this MonsterSchema.

        Monster hit points.

        :return: The hp of this MonsterSchema.
        :rtype: int
        """
        return self._hp

    @hp.setter
    def hp(self, hp):
        """Sets the hp of this MonsterSchema.

        Monster hit points.

        :param hp: The hp of this MonsterSchema.
        :type hp: int
        """
        if hp is None:
            raise ValueError("Invalid value for `hp`, must not be `None`")

        self._hp = hp

    @property
    def attack_fire(self):
        """Gets the attack_fire of this MonsterSchema.

        Monster fire attack.

        :return: The attack_fire of this MonsterSchema.
        :rtype: int
        """
        return self._attack_fire

    @attack_fire.setter
    def attack_fire(self, attack_fire):
        """Sets the attack_fire of this MonsterSchema.

        Monster fire attack.

        :param attack_fire: The attack_fire of this MonsterSchema.
        :type attack_fire: int
        """
        if attack_fire is None:
            raise ValueError("Invalid value for `attack_fire`, must not be `None`")

        self._attack_fire = attack_fire

    @property
    def attack_earth(self):
        """Gets the attack_earth of this MonsterSchema.

        Monster earth attack.

        :return: The attack_earth of this MonsterSchema.
        :rtype: int
        """
        return self._attack_earth

    @attack_earth.setter
    def attack_earth(self, attack_earth):
        """Sets the attack_earth of this MonsterSchema.

        Monster earth attack.

        :param attack_earth: The attack_earth of this MonsterSchema.
        :type attack_earth: int
        """
        if attack_earth is None:
            raise ValueError("Invalid value for `attack_earth`, must not be `None`")

        self._attack_earth = attack_earth

    @property
    def attack_water(self):
        """Gets the attack_water of this MonsterSchema.

        Monster water attack.

        :return: The attack_water of this MonsterSchema.
        :rtype: int
        """
        return self._attack_water

    @attack_water.setter
    def attack_water(self, attack_water):
        """Sets the attack_water of this MonsterSchema.

        Monster water attack.

        :param attack_water: The attack_water of this MonsterSchema.
        :type attack_water: int
        """
        if attack_water is None:
            raise ValueError("Invalid value for `attack_water`, must not be `None`")

        self._attack_water = attack_water

    @property
    def attack_air(self):
        """Gets the attack_air of this MonsterSchema.

        Monster air attack.

        :return: The attack_air of this MonsterSchema.
        :rtype: int
        """
        return self._attack_air

    @attack_air.setter
    def attack_air(self, attack_air):
        """Sets the attack_air of this MonsterSchema.

        Monster air attack.

        :param attack_air: The attack_air of this MonsterSchema.
        :type attack_air: int
        """
        if attack_air is None:
            raise ValueError("Invalid value for `attack_air`, must not be `None`")

        self._attack_air = attack_air

    @property
    def res_fire(self):
        """Gets the res_fire of this MonsterSchema.

        Monster % fire resistance.

        :return: The res_fire of this MonsterSchema.
        :rtype: int
        """
        return self._res_fire

    @res_fire.setter
    def res_fire(self, res_fire):
        """Sets the res_fire of this MonsterSchema.

        Monster % fire resistance.

        :param res_fire: The res_fire of this MonsterSchema.
        :type res_fire: int
        """
        if res_fire is None:
            raise ValueError("Invalid value for `res_fire`, must not be `None`")

        self._res_fire = res_fire

    @property
    def res_earth(self):
        """Gets the res_earth of this MonsterSchema.

        Monster % earth resistance.

        :return: The res_earth of this MonsterSchema.
        :rtype: int
        """
        return self._res_earth

    @res_earth.setter
    def res_earth(self, res_earth):
        """Sets the res_earth of this MonsterSchema.

        Monster % earth resistance.

        :param res_earth: The res_earth of this MonsterSchema.
        :type res_earth: int
        """
        if res_earth is None:
            raise ValueError("Invalid value for `res_earth`, must not be `None`")

        self._res_earth = res_earth

    @property
    def res_water(self):
        """Gets the res_water of this MonsterSchema.

        Monster % water resistance.

        :return: The res_water of this MonsterSchema.
        :rtype: int
        """
        return self._res_water

    @res_water.setter
    def res_water(self, res_water):
        """Sets the res_water of this MonsterSchema.

        Monster % water resistance.

        :param res_water: The res_water of this MonsterSchema.
        :type res_water: int
        """
        if res_water is None:
            raise ValueError("Invalid value for `res_water`, must not be `None`")

        self._res_water = res_water

    @property
    def res_air(self):
        """Gets the res_air of this MonsterSchema.

        Monster % air resistance.

        :return: The res_air of this MonsterSchema.
        :rtype: int
        """
        return self._res_air

    @res_air.setter
    def res_air(self, res_air):
        """Sets the res_air of this MonsterSchema.

        Monster % air resistance.

        :param res_air: The res_air of this MonsterSchema.
        :type res_air: int
        """
        if res_air is None:
            raise ValueError("Invalid value for `res_air`, must not be `None`")

        self._res_air = res_air

    @property
    def critical_strike(self):
        """Gets the critical_strike of this MonsterSchema.

        Monster % critical strike.

        :return: The critical_strike of this MonsterSchema.
        :rtype: int
        """
        return self._critical_strike

    @critical_strike.setter
    def critical_strike(self, critical_strike):
        """Sets the critical_strike of this MonsterSchema.

        Monster % critical strike.

        :param critical_strike: The critical_strike of this MonsterSchema.
        :type critical_strike: int
        """
        if critical_strike is None:
            raise ValueError("Invalid value for `critical_strike`, must not be `None`")

        self._critical_strike = critical_strike

    @property
    def initiative(self):
        """Gets the initiative of this MonsterSchema.

        Monster initiative for turn order.

        :return: The initiative of this MonsterSchema.
        :rtype: int
        """
        return self._initiative

    @initiative.setter
    def initiative(self, initiative):
        """Sets the initiative of this MonsterSchema.

        Monster initiative for turn order.

        :param initiative: The initiative of this MonsterSchema.
        :type initiative: int
        """
        if initiative is None:
            raise ValueError("Invalid value for `initiative`, must not be `None`")

        self._initiative = initiative

    @property
    def effects(self):
        """Gets the effects of this MonsterSchema.

        List of effects.

        :return: The effects of this MonsterSchema.
        :rtype: List[SimpleEffectSchema]
        """
        return self._effects

    @effects.setter
    def effects(self, effects):
        """Sets the effects of this MonsterSchema.

        List of effects.

        :param effects: The effects of this MonsterSchema.
        :type effects: List[SimpleEffectSchema]
        """

        self._effects = effects

    @property
    def min_gold(self):
        """Gets the min_gold of this MonsterSchema.

        Monster minimum gold drop. 

        :return: The min_gold of this MonsterSchema.
        :rtype: int
        """
        return self._min_gold

    @min_gold.setter
    def min_gold(self, min_gold):
        """Sets the min_gold of this MonsterSchema.

        Monster minimum gold drop. 

        :param min_gold: The min_gold of this MonsterSchema.
        :type min_gold: int
        """
        if min_gold is None:
            raise ValueError("Invalid value for `min_gold`, must not be `None`")

        self._min_gold = min_gold

    @property
    def max_gold(self):
        """Gets the max_gold of this MonsterSchema.

        Monster maximum gold drop. 

        :return: The max_gold of this MonsterSchema.
        :rtype: int
        """
        return self._max_gold

    @max_gold.setter
    def max_gold(self, max_gold):
        """Sets the max_gold of this MonsterSchema.

        Monster maximum gold drop. 

        :param max_gold: The max_gold of this MonsterSchema.
        :type max_gold: int
        """
        if max_gold is None:
            raise ValueError("Invalid value for `max_gold`, must not be `None`")

        self._max_gold = max_gold

    @property
    def drops(self):
        """Gets the drops of this MonsterSchema.

        Monster drops. This is a list of items that the monster drops after killing the monster. 

        :return: The drops of this MonsterSchema.
        :rtype: List[DropRateSchema]
        """
        return self._drops

    @drops.setter
    def drops(self, drops):
        """Sets the drops of this MonsterSchema.

        Monster drops. This is a list of items that the monster drops after killing the monster. 

        :param drops: The drops of this MonsterSchema.
        :type drops: List[DropRateSchema]
        """
        if drops is None:
            raise ValueError("Invalid value for `drops`, must not be `None`")

        self._drops = drops
