# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.my_account_details import MyAccountDetails
from artifactsmmo import util


class MyAccountDetailsSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: MyAccountDetails=None):
        """MyAccountDetailsSchema - a model defined in OpenAPI

        :param data: The data of this MyAccountDetailsSchema.
        """
        self.openapi_types = {
            'data': MyAccountDetails
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MyAccountDetailsSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The MyAccountDetailsSchema of this MyAccountDetailsSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this MyAccountDetailsSchema.


        :return: The data of this MyAccountDetailsSchema.
        :rtype: MyAccountDetails
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this MyAccountDetailsSchema.


        :param data: The data of this MyAccountDetailsSchema.
        :type data: MyAccountDetails
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
