# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.account_status import AccountStatus
from artifactsmmo import util


class MyAccountDetails(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username: str=None, email: str=None, member: bool=None, member_expiration: datetime=None, status: AccountStatus=None, badges: List[str]=None, skins: List[str]=None, gems: int=None, event_token: int=None, achievements_points: int=None, banned: bool=None, ban_reason: str=None):
        """MyAccountDetails - a model defined in OpenAPI

        :param username: The username of this MyAccountDetails.
        :param email: The email of this MyAccountDetails.
        :param member: The member of this MyAccountDetails.
        :param member_expiration: The member_expiration of this MyAccountDetails.
        :param status: The status of this MyAccountDetails.
        :param badges: The badges of this MyAccountDetails.
        :param skins: The skins of this MyAccountDetails.
        :param gems: The gems of this MyAccountDetails.
        :param event_token: The event_token of this MyAccountDetails.
        :param achievements_points: The achievements_points of this MyAccountDetails.
        :param banned: The banned of this MyAccountDetails.
        :param ban_reason: The ban_reason of this MyAccountDetails.
        """
        self.openapi_types = {
            'username': str,
            'email': str,
            'member': bool,
            'member_expiration': datetime,
            'status': AccountStatus,
            'badges': List[str],
            'skins': List[str],
            'gems': int,
            'event_token': int,
            'achievements_points': int,
            'banned': bool,
            'ban_reason': str
        }

        self.attribute_map = {
            'username': 'username',
            'email': 'email',
            'member': 'member',
            'member_expiration': 'member_expiration',
            'status': 'status',
            'badges': 'badges',
            'skins': 'skins',
            'gems': 'gems',
            'event_token': 'event_token',
            'achievements_points': 'achievements_points',
            'banned': 'banned',
            'ban_reason': 'ban_reason'
        }

        self._username = username
        self._email = email
        self._member = member
        self._member_expiration = member_expiration
        self._status = status
        self._badges = badges
        self._skins = skins
        self._gems = gems
        self._event_token = event_token
        self._achievements_points = achievements_points
        self._banned = banned
        self._ban_reason = ban_reason

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MyAccountDetails':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The MyAccountDetails of this MyAccountDetails.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this MyAccountDetails.

        Username.

        :return: The username of this MyAccountDetails.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this MyAccountDetails.

        Username.

        :param username: The username of this MyAccountDetails.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")

        self._username = username

    @property
    def email(self):
        """Gets the email of this MyAccountDetails.

        Email.

        :return: The email of this MyAccountDetails.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this MyAccountDetails.

        Email.

        :param email: The email of this MyAccountDetails.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email

    @property
    def member(self):
        """Gets the member of this MyAccountDetails.

        Member status.

        :return: The member of this MyAccountDetails.
        :rtype: bool
        """
        return self._member

    @member.setter
    def member(self, member):
        """Sets the member of this MyAccountDetails.

        Member status.

        :param member: The member of this MyAccountDetails.
        :type member: bool
        """
        if member is None:
            raise ValueError("Invalid value for `member`, must not be `None`")

        self._member = member

    @property
    def member_expiration(self):
        """Gets the member_expiration of this MyAccountDetails.

        Member expiration date.

        :return: The member_expiration of this MyAccountDetails.
        :rtype: datetime
        """
        return self._member_expiration

    @member_expiration.setter
    def member_expiration(self, member_expiration):
        """Sets the member_expiration of this MyAccountDetails.

        Member expiration date.

        :param member_expiration: The member_expiration of this MyAccountDetails.
        :type member_expiration: datetime
        """

        self._member_expiration = member_expiration

    @property
    def status(self):
        """Gets the status of this MyAccountDetails.

        Account status.

        :return: The status of this MyAccountDetails.
        :rtype: AccountStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this MyAccountDetails.

        Account status.

        :param status: The status of this MyAccountDetails.
        :type status: AccountStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")

        self._status = status

    @property
    def badges(self):
        """Gets the badges of this MyAccountDetails.

        Account badges.

        :return: The badges of this MyAccountDetails.
        :rtype: List[str]
        """
        return self._badges

    @badges.setter
    def badges(self, badges):
        """Sets the badges of this MyAccountDetails.

        Account badges.

        :param badges: The badges of this MyAccountDetails.
        :type badges: List[str]
        """

        self._badges = badges

    @property
    def skins(self):
        """Gets the skins of this MyAccountDetails.

        Skins owned.

        :return: The skins of this MyAccountDetails.
        :rtype: List[str]
        """
        return self._skins

    @skins.setter
    def skins(self, skins):
        """Sets the skins of this MyAccountDetails.

        Skins owned.

        :param skins: The skins of this MyAccountDetails.
        :type skins: List[str]
        """
        if skins is None:
            raise ValueError("Invalid value for `skins`, must not be `None`")

        self._skins = skins

    @property
    def gems(self):
        """Gets the gems of this MyAccountDetails.

        Gems.

        :return: The gems of this MyAccountDetails.
        :rtype: int
        """
        return self._gems

    @gems.setter
    def gems(self, gems):
        """Sets the gems of this MyAccountDetails.

        Gems.

        :param gems: The gems of this MyAccountDetails.
        :type gems: int
        """
        if gems is None:
            raise ValueError("Invalid value for `gems`, must not be `None`")

        self._gems = gems

    @property
    def event_token(self):
        """Gets the event_token of this MyAccountDetails.

        Event tokens for spawning events.

        :return: The event_token of this MyAccountDetails.
        :rtype: int
        """
        return self._event_token

    @event_token.setter
    def event_token(self, event_token):
        """Sets the event_token of this MyAccountDetails.

        Event tokens for spawning events.

        :param event_token: The event_token of this MyAccountDetails.
        :type event_token: int
        """
        if event_token is None:
            raise ValueError("Invalid value for `event_token`, must not be `None`")

        self._event_token = event_token

    @property
    def achievements_points(self):
        """Gets the achievements_points of this MyAccountDetails.

        Achievement points.

        :return: The achievements_points of this MyAccountDetails.
        :rtype: int
        """
        return self._achievements_points

    @achievements_points.setter
    def achievements_points(self, achievements_points):
        """Sets the achievements_points of this MyAccountDetails.

        Achievement points.

        :param achievements_points: The achievements_points of this MyAccountDetails.
        :type achievements_points: int
        """
        if achievements_points is None:
            raise ValueError("Invalid value for `achievements_points`, must not be `None`")

        self._achievements_points = achievements_points

    @property
    def banned(self):
        """Gets the banned of this MyAccountDetails.

        Banned.

        :return: The banned of this MyAccountDetails.
        :rtype: bool
        """
        return self._banned

    @banned.setter
    def banned(self, banned):
        """Sets the banned of this MyAccountDetails.

        Banned.

        :param banned: The banned of this MyAccountDetails.
        :type banned: bool
        """
        if banned is None:
            raise ValueError("Invalid value for `banned`, must not be `None`")

        self._banned = banned

    @property
    def ban_reason(self):
        """Gets the ban_reason of this MyAccountDetails.

        Ban reason.

        :return: The ban_reason of this MyAccountDetails.
        :rtype: str
        """
        return self._ban_reason

    @ban_reason.setter
    def ban_reason(self, ban_reason):
        """Sets the ban_reason of this MyAccountDetails.

        Ban reason.

        :param ban_reason: The ban_reason of this MyAccountDetails.
        :type ban_reason: str
        """

        self._ban_reason = ban_reason
