# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.npc_type import NPCType
from artifactsmmo import util


class NPCSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, code: str=None, description: str=None, type: NPCType=None):
        """NPCSchema - a model defined in OpenAPI

        :param name: The name of this NPCSchema.
        :param code: The code of this NPCSchema.
        :param description: The description of this NPCSchema.
        :param type: The type of this NPCSchema.
        """
        self.openapi_types = {
            'name': str,
            'code': str,
            'description': str,
            'type': NPCType
        }

        self.attribute_map = {
            'name': 'name',
            'code': 'code',
            'description': 'description',
            'type': 'type'
        }

        self._name = name
        self._code = code
        self._description = description
        self._type = type

    @classmethod
    def from_dict(cls, dikt: dict) -> 'NPCSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The NPCSchema of this NPCSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this NPCSchema.

        Name of the NPC.

        :return: The name of this NPCSchema.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NPCSchema.

        Name of the NPC.

        :param name: The name of this NPCSchema.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def code(self):
        """Gets the code of this NPCSchema.

        The code of the NPC. This is the NPC's unique identifier (ID).

        :return: The code of this NPCSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this NPCSchema.

        The code of the NPC. This is the NPC's unique identifier (ID).

        :param code: The code of this NPCSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def description(self):
        """Gets the description of this NPCSchema.

        Description of the NPC.

        :return: The description of this NPCSchema.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this NPCSchema.

        Description of the NPC.

        :param description: The description of this NPCSchema.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")

        self._description = description

    @property
    def type(self):
        """Gets the type of this NPCSchema.

        Type of the NPC.

        :return: The type of this NPCSchema.
        :rtype: NPCType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this NPCSchema.

        Type of the NPC.

        :param type: The type of this NPCSchema.
        :type type: NPCType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type
