# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo.models.npc_item_transaction_schema import NpcItemTransactionSchema
from artifactsmmo import util


class NpcMerchantTransactionSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, transaction: NpcItemTransactionSchema=None, character: CharacterSchema=None):
        """NpcMerchantTransactionSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this NpcMerchantTransactionSchema.
        :param transaction: The transaction of this NpcMerchantTransactionSchema.
        :param character: The character of this NpcMerchantTransactionSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'transaction': NpcItemTransactionSchema,
            'character': CharacterSchema
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'transaction': 'transaction',
            'character': 'character'
        }

        self._cooldown = cooldown
        self._transaction = transaction
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'NpcMerchantTransactionSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The NpcMerchantTransactionSchema of this NpcMerchantTransactionSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this NpcMerchantTransactionSchema.

        Cooldown details.

        :return: The cooldown of this NpcMerchantTransactionSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this NpcMerchantTransactionSchema.

        Cooldown details.

        :param cooldown: The cooldown of this NpcMerchantTransactionSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def transaction(self):
        """Gets the transaction of this NpcMerchantTransactionSchema.

        Transaction details.

        :return: The transaction of this NpcMerchantTransactionSchema.
        :rtype: NpcItemTransactionSchema
        """
        return self._transaction

    @transaction.setter
    def transaction(self, transaction):
        """Sets the transaction of this NpcMerchantTransactionSchema.

        Transaction details.

        :param transaction: The transaction of this NpcMerchantTransactionSchema.
        :type transaction: NpcItemTransactionSchema
        """
        if transaction is None:
            raise ValueError("Invalid value for `transaction`, must not be `None`")

        self._transaction = transaction

    @property
    def character(self):
        """Gets the character of this NpcMerchantTransactionSchema.

        Character details.

        :return: The character of this NpcMerchantTransactionSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this NpcMerchantTransactionSchema.

        Character details.

        :param character: The character of this NpcMerchantTransactionSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
