# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class NpcItemTransactionSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, quantity: int=None, currency: str=None, price: int=None, total_price: int=None):
        """NpcItemTransactionSchema - a model defined in OpenAPI

        :param code: The code of this NpcItemTransactionSchema.
        :param quantity: The quantity of this NpcItemTransactionSchema.
        :param currency: The currency of this NpcItemTransactionSchema.
        :param price: The price of this NpcItemTransactionSchema.
        :param total_price: The total_price of this NpcItemTransactionSchema.
        """
        self.openapi_types = {
            'code': str,
            'quantity': int,
            'currency': str,
            'price': int,
            'total_price': int
        }

        self.attribute_map = {
            'code': 'code',
            'quantity': 'quantity',
            'currency': 'currency',
            'price': 'price',
            'total_price': 'total_price'
        }

        self._code = code
        self._quantity = quantity
        self._currency = currency
        self._price = price
        self._total_price = total_price

    @classmethod
    def from_dict(cls, dikt: dict) -> 'NpcItemTransactionSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The NpcItemTransactionSchema of this NpcItemTransactionSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this NpcItemTransactionSchema.

        Item code.

        :return: The code of this NpcItemTransactionSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this NpcItemTransactionSchema.

        Item code.

        :param code: The code of this NpcItemTransactionSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def quantity(self):
        """Gets the quantity of this NpcItemTransactionSchema.

        Item quantity.

        :return: The quantity of this NpcItemTransactionSchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this NpcItemTransactionSchema.

        Item quantity.

        :param quantity: The quantity of this NpcItemTransactionSchema.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")

        self._quantity = quantity

    @property
    def currency(self):
        """Gets the currency of this NpcItemTransactionSchema.

        Currency used for the transaction.

        :return: The currency of this NpcItemTransactionSchema.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this NpcItemTransactionSchema.

        Currency used for the transaction.

        :param currency: The currency of this NpcItemTransactionSchema.
        :type currency: str
        """
        if currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")

        self._currency = currency

    @property
    def price(self):
        """Gets the price of this NpcItemTransactionSchema.

        Item price.

        :return: The price of this NpcItemTransactionSchema.
        :rtype: int
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this NpcItemTransactionSchema.

        Item price.

        :param price: The price of this NpcItemTransactionSchema.
        :type price: int
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")

        self._price = price

    @property
    def total_price(self):
        """Gets the total_price of this NpcItemTransactionSchema.

        Total price of the transaction.

        :return: The total_price of this NpcItemTransactionSchema.
        :rtype: int
        """
        return self._total_price

    @total_price.setter
    def total_price(self, total_price):
        """Sets the total_price of this NpcItemTransactionSchema.

        Total price of the transaction.

        :param total_price: The total_price of this NpcItemTransactionSchema.
        :type total_price: int
        """
        if total_price is None:
            raise ValueError("Invalid value for `total_price`, must not be `None`")

        self._total_price = total_price
