# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.npc_schema import NPCSchema
from artifactsmmo import util


class NPCResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: NPCSchema=None):
        """NPCResponseSchema - a model defined in OpenAPI

        :param data: The data of this NPCResponseSchema.
        """
        self.openapi_types = {
            'data': NPCSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'NPCResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The NPCResponseSchema of this NPCResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this NPCResponseSchema.


        :return: The data of this NPCResponseSchema.
        :rtype: NPCSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this NPCResponseSchema.


        :param data: The data of this NPCResponseSchema.
        :type data: NPCSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
