# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class NPCItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, npc: str=None, currency: str=None, buy_price: int=None, sell_price: int=None):
        """NPCItem - a model defined in OpenAPI

        :param code: The code of this NPCItem.
        :param npc: The npc of this NPCItem.
        :param currency: The currency of this NPCItem.
        :param buy_price: The buy_price of this NPCItem.
        :param sell_price: The sell_price of this NPCItem.
        """
        self.openapi_types = {
            'code': str,
            'npc': str,
            'currency': str,
            'buy_price': int,
            'sell_price': int
        }

        self.attribute_map = {
            'code': 'code',
            'npc': 'npc',
            'currency': 'currency',
            'buy_price': 'buy_price',
            'sell_price': 'sell_price'
        }

        self._code = code
        self._npc = npc
        self._currency = currency
        self._buy_price = buy_price
        self._sell_price = sell_price

    @classmethod
    def from_dict(cls, dikt: dict) -> 'NPCItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The NPCItem of this NPCItem.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this NPCItem.

        The code of the NPC. This is the NPC's unique identifier (ID).

        :return: The code of this NPCItem.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this NPCItem.

        The code of the NPC. This is the NPC's unique identifier (ID).

        :param code: The code of this NPCItem.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def npc(self):
        """Gets the npc of this NPCItem.

        Code of the NPC that sells/buys the item.

        :return: The npc of this NPCItem.
        :rtype: str
        """
        return self._npc

    @npc.setter
    def npc(self, npc):
        """Sets the npc of this NPCItem.

        Code of the NPC that sells/buys the item.

        :param npc: The npc of this NPCItem.
        :type npc: str
        """
        if npc is None:
            raise ValueError("Invalid value for `npc`, must not be `None`")

        self._npc = npc

    @property
    def currency(self):
        """Gets the currency of this NPCItem.

        Currency used to buy/sell the item. If it's not gold, it's the item code.

        :return: The currency of this NPCItem.
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this NPCItem.

        Currency used to buy/sell the item. If it's not gold, it's the item code.

        :param currency: The currency of this NPCItem.
        :type currency: str
        """
        if currency is None:
            raise ValueError("Invalid value for `currency`, must not be `None`")

        self._currency = currency

    @property
    def buy_price(self):
        """Gets the buy_price of this NPCItem.

        Price to buy the item.

        :return: The buy_price of this NPCItem.
        :rtype: int
        """
        return self._buy_price

    @buy_price.setter
    def buy_price(self, buy_price):
        """Sets the buy_price of this NPCItem.

        Price to buy the item.

        :param buy_price: The buy_price of this NPCItem.
        :type buy_price: int
        """

        self._buy_price = buy_price

    @property
    def sell_price(self):
        """Gets the sell_price of this NPCItem.

        Price to sell the item.

        :return: The sell_price of this NPCItem.
        :rtype: int
        """
        return self._sell_price

    @sell_price.setter
    def sell_price(self, sell_price):
        """Sets the sell_price of this NPCItem.

        Price to sell the item.

        :param sell_price: The sell_price of this NPCItem.
        :type sell_price: int
        """

        self._sell_price = sell_price
