# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class PasswordResetRequestSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email: str=None):
        """PasswordResetRequestSchema - a model defined in OpenAPI

        :param email: The email of this PasswordResetRequestSchema.
        """
        self.openapi_types = {
            'email': str
        }

        self.attribute_map = {
            'email': 'email'
        }

        self._email = email

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PasswordResetRequestSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PasswordResetRequestSchema of this PasswordResetRequestSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self):
        """Gets the email of this PasswordResetRequestSchema.

        Your email address.

        :return: The email of this PasswordResetRequestSchema.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this PasswordResetRequestSchema.

        Your email address.

        :param email: The email of this PasswordResetRequestSchema.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")

        self._email = email
