# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.pending_item_source import PendingItemSource
from artifactsmmo.models.simple_item_schema import SimpleItemSchema
from artifactsmmo import util


class PendingItemSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, account: str=None, source: PendingItemSource=None, source_id: str=None, description: str=None, gold: int=0, items: List[SimpleItemSchema]=None, created_at: datetime=None, claimed_at: datetime=None):
        """PendingItemSchema - a model defined in OpenAPI

        :param id: The id of this PendingItemSchema.
        :param account: The account of this PendingItemSchema.
        :param source: The source of this PendingItemSchema.
        :param source_id: The source_id of this PendingItemSchema.
        :param description: The description of this PendingItemSchema.
        :param gold: The gold of this PendingItemSchema.
        :param items: The items of this PendingItemSchema.
        :param created_at: The created_at of this PendingItemSchema.
        :param claimed_at: The claimed_at of this PendingItemSchema.
        """
        self.openapi_types = {
            'id': str,
            'account': str,
            'source': PendingItemSource,
            'source_id': str,
            'description': str,
            'gold': int,
            'items': List[SimpleItemSchema],
            'created_at': datetime,
            'claimed_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'account': 'account',
            'source': 'source',
            'source_id': 'source_id',
            'description': 'description',
            'gold': 'gold',
            'items': 'items',
            'created_at': 'created_at',
            'claimed_at': 'claimed_at'
        }

        self._id = id
        self._account = account
        self._source = source
        self._source_id = source_id
        self._description = description
        self._gold = gold
        self._items = items
        self._created_at = created_at
        self._claimed_at = claimed_at

    @classmethod
    def from_dict(cls, dikt: dict) -> 'PendingItemSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The PendingItemSchema of this PendingItemSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this PendingItemSchema.

        Pending item ID.

        :return: The id of this PendingItemSchema.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PendingItemSchema.

        Pending item ID.

        :param id: The id of this PendingItemSchema.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id

    @property
    def account(self):
        """Gets the account of this PendingItemSchema.

        Account username.

        :return: The account of this PendingItemSchema.
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this PendingItemSchema.

        Account username.

        :param account: The account of this PendingItemSchema.
        :type account: str
        """
        if account is None:
            raise ValueError("Invalid value for `account`, must not be `None`")

        self._account = account

    @property
    def source(self):
        """Gets the source of this PendingItemSchema.

        Source of the pending item.

        :return: The source of this PendingItemSchema.
        :rtype: PendingItemSource
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this PendingItemSchema.

        Source of the pending item.

        :param source: The source of this PendingItemSchema.
        :type source: PendingItemSource
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")

        self._source = source

    @property
    def source_id(self):
        """Gets the source_id of this PendingItemSchema.

        ID reference for the source (e.g., achievement code, order id).

        :return: The source_id of this PendingItemSchema.
        :rtype: str
        """
        return self._source_id

    @source_id.setter
    def source_id(self, source_id):
        """Sets the source_id of this PendingItemSchema.

        ID reference for the source (e.g., achievement code, order id).

        :param source_id: The source_id of this PendingItemSchema.
        :type source_id: str
        """

        self._source_id = source_id

    @property
    def description(self):
        """Gets the description of this PendingItemSchema.

        Description for display.

        :return: The description of this PendingItemSchema.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PendingItemSchema.

        Description for display.

        :param description: The description of this PendingItemSchema.
        :type description: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")

        self._description = description

    @property
    def gold(self):
        """Gets the gold of this PendingItemSchema.

        Gold amount.

        :return: The gold of this PendingItemSchema.
        :rtype: int
        """
        return self._gold

    @gold.setter
    def gold(self, gold):
        """Sets the gold of this PendingItemSchema.

        Gold amount.

        :param gold: The gold of this PendingItemSchema.
        :type gold: int
        """

        self._gold = gold

    @property
    def items(self):
        """Gets the items of this PendingItemSchema.

        List of items to be claimed.

        :return: The items of this PendingItemSchema.
        :rtype: List[SimpleItemSchema]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this PendingItemSchema.

        List of items to be claimed.

        :param items: The items of this PendingItemSchema.
        :type items: List[SimpleItemSchema]
        """

        self._items = items

    @property
    def created_at(self):
        """Gets the created_at of this PendingItemSchema.

        When the pending item was created.

        :return: The created_at of this PendingItemSchema.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this PendingItemSchema.

        When the pending item was created.

        :param created_at: The created_at of this PendingItemSchema.
        :type created_at: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")

        self._created_at = created_at

    @property
    def claimed_at(self):
        """Gets the claimed_at of this PendingItemSchema.

        When the pending item was claimed.

        :return: The claimed_at of this PendingItemSchema.
        :rtype: datetime
        """
        return self._claimed_at

    @claimed_at.setter
    def claimed_at(self, claimed_at):
        """Sets the claimed_at of this PendingItemSchema.

        When the pending item was claimed.

        :param claimed_at: The claimed_at of this PendingItemSchema.
        :type claimed_at: datetime
        """

        self._claimed_at = claimed_at
