# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.drop_schema import DropSchema
from artifactsmmo import util


class RecyclingItemsSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items: List[DropSchema]=None):
        """RecyclingItemsSchema - a model defined in OpenAPI

        :param items: The items of this RecyclingItemsSchema.
        """
        self.openapi_types = {
            'items': List[DropSchema]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RecyclingItemsSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RecyclingItemsSchema of this RecyclingItemsSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this RecyclingItemsSchema.

        Objects received.

        :return: The items of this RecyclingItemsSchema.
        :rtype: List[DropSchema]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this RecyclingItemsSchema.

        Objects received.

        :param items: The items of this RecyclingItemsSchema.
        :type items: List[DropSchema]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")

        self._items = items
