# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.recycling_data_schema import RecyclingDataSchema
from artifactsmmo import util


class RecyclingResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: RecyclingDataSchema=None):
        """RecyclingResponseSchema - a model defined in OpenAPI

        :param data: The data of this RecyclingResponseSchema.
        """
        self.openapi_types = {
            'data': RecyclingDataSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RecyclingResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RecyclingResponseSchema of this RecyclingResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this RecyclingResponseSchema.


        :return: The data of this RecyclingResponseSchema.
        :rtype: RecyclingDataSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this RecyclingResponseSchema.


        :param data: The data of this RecyclingResponseSchema.
        :type data: RecyclingDataSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
