# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo.models.recycling_items_schema import RecyclingItemsSchema
from artifactsmmo import util


class RecyclingDataSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, details: RecyclingItemsSchema=None, character: CharacterSchema=None):
        """RecyclingDataSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this RecyclingDataSchema.
        :param details: The details of this RecyclingDataSchema.
        :param character: The character of this RecyclingDataSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'details': RecyclingItemsSchema,
            'character': CharacterSchema
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'details': 'details',
            'character': 'character'
        }

        self._cooldown = cooldown
        self._details = details
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RecyclingDataSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RecyclingDataSchema of this RecyclingDataSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this RecyclingDataSchema.

        Cooldown details.

        :return: The cooldown of this RecyclingDataSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this RecyclingDataSchema.

        Cooldown details.

        :param cooldown: The cooldown of this RecyclingDataSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def details(self):
        """Gets the details of this RecyclingDataSchema.

        Craft details.

        :return: The details of this RecyclingDataSchema.
        :rtype: RecyclingItemsSchema
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this RecyclingDataSchema.

        Craft details.

        :param details: The details of this RecyclingDataSchema.
        :type details: RecyclingItemsSchema
        """
        if details is None:
            raise ValueError("Invalid value for `details`, must not be `None`")

        self._details = details

    @property
    def character(self):
        """Gets the character of this RecyclingDataSchema.

        Player details.

        :return: The character of this RecyclingDataSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this RecyclingDataSchema.

        Player details.

        :param character: The character of this RecyclingDataSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
