# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.resource_schema import ResourceSchema
from artifactsmmo import util


class ResourceResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: ResourceSchema=None):
        """ResourceResponseSchema - a model defined in OpenAPI

        :param data: The data of this ResourceResponseSchema.
        """
        self.openapi_types = {
            'data': ResourceSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ResourceResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ResourceResponseSchema of this ResourceResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this ResourceResponseSchema.


        :return: The data of this ResourceResponseSchema.
        :rtype: ResourceSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ResourceResponseSchema.


        :param data: The data of this ResourceResponseSchema.
        :type data: ResourceSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
