# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.simple_item_schema import SimpleItemSchema
from artifactsmmo import util


class RewardsSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items: List[SimpleItemSchema]=None, gold: int=None):
        """RewardsSchema - a model defined in OpenAPI

        :param items: The items of this RewardsSchema.
        :param gold: The gold of this RewardsSchema.
        """
        self.openapi_types = {
            'items': List[SimpleItemSchema],
            'gold': int
        }

        self.attribute_map = {
            'items': 'items',
            'gold': 'gold'
        }

        self._items = items
        self._gold = gold

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RewardsSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RewardsSchema of this RewardsSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self):
        """Gets the items of this RewardsSchema.

        Items rewards.

        :return: The items of this RewardsSchema.
        :rtype: List[SimpleItemSchema]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this RewardsSchema.

        Items rewards.

        :param items: The items of this RewardsSchema.
        :type items: List[SimpleItemSchema]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")

        self._items = items

    @property
    def gold(self):
        """Gets the gold of this RewardsSchema.

        Gold rewards.

        :return: The gold of this RewardsSchema.
        :rtype: int
        """
        return self._gold

    @gold.setter
    def gold(self, gold):
        """Sets the gold of this RewardsSchema.

        Gold rewards.

        :param gold: The gold of this RewardsSchema.
        :type gold: int
        """
        if gold is None:
            raise ValueError("Invalid value for `gold`, must not be `None`")

        self._gold = gold
