# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.drop_rate_schema import DropRateSchema
from artifactsmmo import util


class RewardResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: DropRateSchema=None):
        """RewardResponseSchema - a model defined in OpenAPI

        :param data: The data of this RewardResponseSchema.
        """
        self.openapi_types = {
            'data': DropRateSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RewardResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RewardResponseSchema of this RewardResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this RewardResponseSchema.


        :return: The data of this RewardResponseSchema.
        :rtype: DropRateSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this RewardResponseSchema.


        :param data: The data of this RewardResponseSchema.
        :type data: DropRateSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
