# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.reward_data_schema import RewardDataSchema
from artifactsmmo import util


class RewardDataResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: RewardDataSchema=None):
        """RewardDataResponseSchema - a model defined in OpenAPI

        :param data: The data of this RewardDataResponseSchema.
        """
        self.openapi_types = {
            'data': RewardDataSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RewardDataResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The RewardDataResponseSchema of this RewardDataResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this RewardDataResponseSchema.


        :return: The data of this RewardDataResponseSchema.
        :rtype: RewardDataSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this RewardDataResponseSchema.


        :param data: The data of this RewardDataResponseSchema.
        :type data: RewardDataSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
