# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo import util


class SandboxSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, character: CharacterSchema=None):
        """SandboxSchema - a model defined in OpenAPI

        :param character: The character of this SandboxSchema.
        """
        self.openapi_types = {
            'character': CharacterSchema
        }

        self.attribute_map = {
            'character': 'character'
        }

        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SandboxSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SandboxSchema of this SandboxSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def character(self):
        """Gets the character of this SandboxSchema.

        Character details.

        :return: The character of this SandboxSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this SandboxSchema.

        Character details.

        :param character: The character of this SandboxSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
