# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.sandbox_schema import SandboxSchema
from artifactsmmo import util


class SandboxResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: SandboxSchema=None):
        """SandboxResponseSchema - a model defined in OpenAPI

        :param data: The data of this SandboxResponseSchema.
        """
        self.openapi_types = {
            'data': SandboxSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SandboxResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SandboxResponseSchema of this SandboxResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this SandboxResponseSchema.

        Sandbox action data.

        :return: The data of this SandboxResponseSchema.
        :rtype: SandboxSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this SandboxResponseSchema.

        Sandbox action data.

        :param data: The data of this SandboxResponseSchema.
        :type data: SandboxSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
