# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
import re
from artifactsmmo import util


class SandboxGiveItemSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, quantity: int=None, character: str=None):
        """SandboxGiveItemSchema - a model defined in OpenAPI

        :param code: The code of this SandboxGiveItemSchema.
        :param quantity: The quantity of this SandboxGiveItemSchema.
        :param character: The character of this SandboxGiveItemSchema.
        """
        self.openapi_types = {
            'code': str,
            'quantity': int,
            'character': str
        }

        self.attribute_map = {
            'code': 'code',
            'quantity': 'quantity',
            'character': 'character'
        }

        self._code = code
        self._quantity = quantity
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SandboxGiveItemSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SandboxGiveItemSchema of this SandboxGiveItemSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this SandboxGiveItemSchema.

        Item code.

        :return: The code of this SandboxGiveItemSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this SandboxGiveItemSchema.

        Item code.

        :param code: The code of this SandboxGiveItemSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")
        if code is not None and not re.search(r'^[a-zA-Z0-9_-]+$', code):
            raise ValueError("Invalid value for `code`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._code = code

    @property
    def quantity(self):
        """Gets the quantity of this SandboxGiveItemSchema.

        Item quantity.

        :return: The quantity of this SandboxGiveItemSchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this SandboxGiveItemSchema.

        Item quantity.

        :param quantity: The quantity of this SandboxGiveItemSchema.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")
        if quantity is not None and quantity < 1:
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `1`")

        self._quantity = quantity

    @property
    def character(self):
        """Gets the character of this SandboxGiveItemSchema.

        Character name. The name of the character who will receive the item.

        :return: The character of this SandboxGiveItemSchema.
        :rtype: str
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this SandboxGiveItemSchema.

        Character name. The name of the character who will receive the item.

        :param character: The character of this SandboxGiveItemSchema.
        :type character: str
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")
        if character is not None and not re.search(r'^[a-zA-Z0-9_-]+$', character):
            raise ValueError("Invalid value for `character`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._character = character
