# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
import re
from artifactsmmo import util


class SimpleItemSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, quantity: int=None):
        """SimpleItemSchema - a model defined in OpenAPI

        :param code: The code of this SimpleItemSchema.
        :param quantity: The quantity of this SimpleItemSchema.
        """
        self.openapi_types = {
            'code': str,
            'quantity': int
        }

        self.attribute_map = {
            'code': 'code',
            'quantity': 'quantity'
        }

        self._code = code
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SimpleItemSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SimpleItemSchema of this SimpleItemSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this SimpleItemSchema.

        Item code.

        :return: The code of this SimpleItemSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this SimpleItemSchema.

        Item code.

        :param code: The code of this SimpleItemSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")
        if code is not None and not re.search(r'^[a-zA-Z0-9_-]+$', code):
            raise ValueError("Invalid value for `code`, must be a follow pattern or equal to `/^[a-zA-Z0-9_-]+$/`")

        self._code = code

    @property
    def quantity(self):
        """Gets the quantity of this SimpleItemSchema.

        Item quantity.

        :return: The quantity of this SimpleItemSchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this SimpleItemSchema.

        Item quantity.

        :param quantity: The quantity of this SimpleItemSchema.
        :type quantity: int
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")
        if quantity is not None and quantity < 1:
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `1`")

        self._quantity = quantity
