# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.drop_schema import DropSchema
from artifactsmmo import util


class SkillInfoSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, xp: int=None, items: List[DropSchema]=None):
        """SkillInfoSchema - a model defined in OpenAPI

        :param xp: The xp of this SkillInfoSchema.
        :param items: The items of this SkillInfoSchema.
        """
        self.openapi_types = {
            'xp': int,
            'items': List[DropSchema]
        }

        self.attribute_map = {
            'xp': 'xp',
            'items': 'items'
        }

        self._xp = xp
        self._items = items

    @classmethod
    def from_dict(cls, dikt: dict) -> 'SkillInfoSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The SkillInfoSchema of this SkillInfoSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def xp(self):
        """Gets the xp of this SkillInfoSchema.

        The amount of xp gained.

        :return: The xp of this SkillInfoSchema.
        :rtype: int
        """
        return self._xp

    @xp.setter
    def xp(self, xp):
        """Sets the xp of this SkillInfoSchema.

        The amount of xp gained.

        :param xp: The xp of this SkillInfoSchema.
        :type xp: int
        """
        if xp is None:
            raise ValueError("Invalid value for `xp`, must not be `None`")

        self._xp = xp

    @property
    def items(self):
        """Gets the items of this SkillInfoSchema.

        Objects received.

        :return: The items of this SkillInfoSchema.
        :rtype: List[DropSchema]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this SkillInfoSchema.

        Objects received.

        :param items: The items of this SkillInfoSchema.
        :type items: List[DropSchema]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")

        self._items = items
