# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.status_schema import StatusSchema
from artifactsmmo import util


class StatusResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: StatusSchema=None):
        """StatusResponseSchema - a model defined in OpenAPI

        :param data: The data of this StatusResponseSchema.
        """
        self.openapi_types = {
            'data': StatusSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'StatusResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The StatusResponseSchema of this StatusResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this StatusResponseSchema.


        :return: The data of this StatusResponseSchema.
        :rtype: StatusSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this StatusResponseSchema.


        :param data: The data of this StatusResponseSchema.
        :type data: StatusSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
