# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.character_schema import CharacterSchema
from artifactsmmo.models.cooldown_schema import CooldownSchema
from artifactsmmo.models.task_trade_schema import TaskTradeSchema
from artifactsmmo import util


class TaskTradeDataSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cooldown: CooldownSchema=None, trade: TaskTradeSchema=None, character: CharacterSchema=None):
        """TaskTradeDataSchema - a model defined in OpenAPI

        :param cooldown: The cooldown of this TaskTradeDataSchema.
        :param trade: The trade of this TaskTradeDataSchema.
        :param character: The character of this TaskTradeDataSchema.
        """
        self.openapi_types = {
            'cooldown': CooldownSchema,
            'trade': TaskTradeSchema,
            'character': CharacterSchema
        }

        self.attribute_map = {
            'cooldown': 'cooldown',
            'trade': 'trade',
            'character': 'character'
        }

        self._cooldown = cooldown
        self._trade = trade
        self._character = character

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TaskTradeDataSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TaskTradeDataSchema of this TaskTradeDataSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cooldown(self):
        """Gets the cooldown of this TaskTradeDataSchema.

        Cooldown details.

        :return: The cooldown of this TaskTradeDataSchema.
        :rtype: CooldownSchema
        """
        return self._cooldown

    @cooldown.setter
    def cooldown(self, cooldown):
        """Sets the cooldown of this TaskTradeDataSchema.

        Cooldown details.

        :param cooldown: The cooldown of this TaskTradeDataSchema.
        :type cooldown: CooldownSchema
        """
        if cooldown is None:
            raise ValueError("Invalid value for `cooldown`, must not be `None`")

        self._cooldown = cooldown

    @property
    def trade(self):
        """Gets the trade of this TaskTradeDataSchema.

        Reward details.

        :return: The trade of this TaskTradeDataSchema.
        :rtype: TaskTradeSchema
        """
        return self._trade

    @trade.setter
    def trade(self, trade):
        """Sets the trade of this TaskTradeDataSchema.

        Reward details.

        :param trade: The trade of this TaskTradeDataSchema.
        :type trade: TaskTradeSchema
        """
        if trade is None:
            raise ValueError("Invalid value for `trade`, must not be `None`")

        self._trade = trade

    @property
    def character(self):
        """Gets the character of this TaskTradeDataSchema.

        Player details.

        :return: The character of this TaskTradeDataSchema.
        :rtype: CharacterSchema
        """
        return self._character

    @character.setter
    def character(self, character):
        """Sets the character of this TaskTradeDataSchema.

        Player details.

        :param character: The character of this TaskTradeDataSchema.
        :type character: CharacterSchema
        """
        if character is None:
            raise ValueError("Invalid value for `character`, must not be `None`")

        self._character = character
