# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.task_full_schema import TaskFullSchema
from artifactsmmo import util


class TaskFullResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: TaskFullSchema=None):
        """TaskFullResponseSchema - a model defined in OpenAPI

        :param data: The data of this TaskFullResponseSchema.
        """
        self.openapi_types = {
            'data': TaskFullSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TaskFullResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TaskFullResponseSchema of this TaskFullResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this TaskFullResponseSchema.


        :return: The data of this TaskFullResponseSchema.
        :rtype: TaskFullSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this TaskFullResponseSchema.


        :param data: The data of this TaskFullResponseSchema.
        :type data: TaskFullSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
