# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.task_data_schema import TaskDataSchema
from artifactsmmo import util


class TaskResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data: TaskDataSchema=None):
        """TaskResponseSchema - a model defined in OpenAPI

        :param data: The data of this TaskResponseSchema.
        """
        self.openapi_types = {
            'data': TaskDataSchema
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TaskResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TaskResponseSchema of this TaskResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self):
        """Gets the data of this TaskResponseSchema.


        :return: The data of this TaskResponseSchema.
        :rtype: TaskDataSchema
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this TaskResponseSchema.


        :param data: The data of this TaskResponseSchema.
        :type data: TaskDataSchema
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")

        self._data = data
