# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.rewards_schema import RewardsSchema
from artifactsmmo.models.task_type import TaskType
from artifactsmmo import util


class TaskSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, type: TaskType=None, total: int=None, rewards: RewardsSchema=None):
        """TaskSchema - a model defined in OpenAPI

        :param code: The code of this TaskSchema.
        :param type: The type of this TaskSchema.
        :param total: The total of this TaskSchema.
        :param rewards: The rewards of this TaskSchema.
        """
        self.openapi_types = {
            'code': str,
            'type': TaskType,
            'total': int,
            'rewards': RewardsSchema
        }

        self.attribute_map = {
            'code': 'code',
            'type': 'type',
            'total': 'total',
            'rewards': 'rewards'
        }

        self._code = code
        self._type = type
        self._total = total
        self._rewards = rewards

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TaskSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TaskSchema of this TaskSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this TaskSchema.

        Task objective.

        :return: The code of this TaskSchema.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this TaskSchema.

        Task objective.

        :param code: The code of this TaskSchema.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    @property
    def type(self):
        """Gets the type of this TaskSchema.

        The type of task.

        :return: The type of this TaskSchema.
        :rtype: TaskType
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this TaskSchema.

        The type of task.

        :param type: The type of this TaskSchema.
        :type type: TaskType
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")

        self._type = type

    @property
    def total(self):
        """Gets the total of this TaskSchema.

        The total required to complete the task.

        :return: The total of this TaskSchema.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this TaskSchema.

        The total required to complete the task.

        :param total: The total of this TaskSchema.
        :type total: int
        """
        if total is None:
            raise ValueError("Invalid value for `total`, must not be `None`")

        self._total = total

    @property
    def rewards(self):
        """Gets the rewards of this TaskSchema.

        Rewards for completing the task.

        :return: The rewards of this TaskSchema.
        :rtype: RewardsSchema
        """
        return self._rewards

    @rewards.setter
    def rewards(self, rewards):
        """Sets the rewards of this TaskSchema.

        Rewards for completing the task.

        :param rewards: The rewards of this TaskSchema.
        :type rewards: RewardsSchema
        """
        if rewards is None:
            raise ValueError("Invalid value for `rewards`, must not be `None`")

        self._rewards = rewards
