# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo import util


class TokenResponseSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, token: str=None):
        """TokenResponseSchema - a model defined in OpenAPI

        :param token: The token of this TokenResponseSchema.
        """
        self.openapi_types = {
            'token': str
        }

        self.attribute_map = {
            'token': 'token'
        }

        self._token = token

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TokenResponseSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TokenResponseSchema of this TokenResponseSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self):
        """Gets the token of this TokenResponseSchema.


        :return: The token of this TokenResponseSchema.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this TokenResponseSchema.


        :param token: The token of this TokenResponseSchema.
        :type token: str
        """
        if token is None:
            raise ValueError("Invalid value for `token`, must not be `None`")

        self._token = token
