# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.condition_schema import ConditionSchema
from artifactsmmo.models.map_layer import MapLayer
from artifactsmmo import util


class TransitionSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, map_id: int=None, x: int=None, y: int=None, layer: MapLayer=None, conditions: List[ConditionSchema]=None):
        """TransitionSchema - a model defined in OpenAPI

        :param map_id: The map_id of this TransitionSchema.
        :param x: The x of this TransitionSchema.
        :param y: The y of this TransitionSchema.
        :param layer: The layer of this TransitionSchema.
        :param conditions: The conditions of this TransitionSchema.
        """
        self.openapi_types = {
            'map_id': int,
            'x': int,
            'y': int,
            'layer': MapLayer,
            'conditions': List[ConditionSchema]
        }

        self.attribute_map = {
            'map_id': 'map_id',
            'x': 'x',
            'y': 'y',
            'layer': 'layer',
            'conditions': 'conditions'
        }

        self._map_id = map_id
        self._x = x
        self._y = y
        self._layer = layer
        self._conditions = conditions

    @classmethod
    def from_dict(cls, dikt: dict) -> 'TransitionSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The TransitionSchema of this TransitionSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def map_id(self):
        """Gets the map_id of this TransitionSchema.

        ID of the destination map.

        :return: The map_id of this TransitionSchema.
        :rtype: int
        """
        return self._map_id

    @map_id.setter
    def map_id(self, map_id):
        """Sets the map_id of this TransitionSchema.

        ID of the destination map.

        :param map_id: The map_id of this TransitionSchema.
        :type map_id: int
        """
        if map_id is None:
            raise ValueError("Invalid value for `map_id`, must not be `None`")

        self._map_id = map_id

    @property
    def x(self):
        """Gets the x of this TransitionSchema.

        Position X of the destination.

        :return: The x of this TransitionSchema.
        :rtype: int
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this TransitionSchema.

        Position X of the destination.

        :param x: The x of this TransitionSchema.
        :type x: int
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")

        self._x = x

    @property
    def y(self):
        """Gets the y of this TransitionSchema.

        Position Y of the destination.

        :return: The y of this TransitionSchema.
        :rtype: int
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this TransitionSchema.

        Position Y of the destination.

        :param y: The y of this TransitionSchema.
        :type y: int
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")

        self._y = y

    @property
    def layer(self):
        """Gets the layer of this TransitionSchema.

        Layer of the destination.

        :return: The layer of this TransitionSchema.
        :rtype: MapLayer
        """
        return self._layer

    @layer.setter
    def layer(self, layer):
        """Sets the layer of this TransitionSchema.

        Layer of the destination.

        :param layer: The layer of this TransitionSchema.
        :type layer: MapLayer
        """
        if layer is None:
            raise ValueError("Invalid value for `layer`, must not be `None`")

        self._layer = layer

    @property
    def conditions(self):
        """Gets the conditions of this TransitionSchema.

        Conditions for the transition.

        :return: The conditions of this TransitionSchema.
        :rtype: List[ConditionSchema]
        """
        return self._conditions

    @conditions.setter
    def conditions(self, conditions):
        """Sets the conditions of this TransitionSchema.

        Conditions for the transition.

        :param conditions: The conditions of this TransitionSchema.
        :type conditions: List[ConditionSchema]
        """

        self._conditions = conditions
