# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from artifactsmmo.models.base_model import Model
from artifactsmmo.models.item_slot import ItemSlot
from artifactsmmo import util


class UnequipSchema(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, slot: ItemSlot=None, quantity: int=1):
        """UnequipSchema - a model defined in OpenAPI

        :param slot: The slot of this UnequipSchema.
        :param quantity: The quantity of this UnequipSchema.
        """
        self.openapi_types = {
            'slot': ItemSlot,
            'quantity': int
        }

        self.attribute_map = {
            'slot': 'slot',
            'quantity': 'quantity'
        }

        self._slot = slot
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt: dict) -> 'UnequipSchema':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The UnequipSchema of this UnequipSchema.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def slot(self):
        """Gets the slot of this UnequipSchema.

        Item slot.

        :return: The slot of this UnequipSchema.
        :rtype: ItemSlot
        """
        return self._slot

    @slot.setter
    def slot(self, slot):
        """Sets the slot of this UnequipSchema.

        Item slot.

        :param slot: The slot of this UnequipSchema.
        :type slot: ItemSlot
        """
        if slot is None:
            raise ValueError("Invalid value for `slot`, must not be `None`")

        self._slot = slot

    @property
    def quantity(self):
        """Gets the quantity of this UnequipSchema.

        Item quantity. Applicable to utilities only.

        :return: The quantity of this UnequipSchema.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this UnequipSchema.

        Item quantity. Applicable to utilities only.

        :param quantity: The quantity of this UnequipSchema.
        :type quantity: int
        """
        if quantity is not None and quantity > 100:
            raise ValueError("Invalid value for `quantity`, must be a value less than or equal to `100`")
        if quantity is not None and quantity < 1:
            raise ValueError("Invalid value for `quantity`, must be a value greater than or equal to `1`")

        self._quantity = quantity
